# Pre-processing MultiplEYE Data

This notebook provides a step-by-step guide through how to process the eye-tracking data and the psychometric tests data collected within the MultiplEYE project. This goal of this notebook is twofold:

1. To provide a step-by-step guide on how to preprocess MultiplEYE data using the `pymovements` library and our custom preprocessing functions.
2. To serve as a tutorial for researchers who want to preprocess their own MultiplEYE data, or data from other eye-tracking datasets, using the `pymovements` library.

## Preparation steps
1. Download the data folder from the online repository. Note that this is only possible if you have access to at least one data collection protected folder. You will have access if you are an active member of one data collection group. Download the entire content of the folder.
When you download it from SwitchDrive, it will automatically create a .tar file.
2. Add the folder to the `data/` folder in this repo. The name of the folder is the data collection name, e.g., `MultiplEYE_ZH_CH_Zurich_1_2025`.
3. Extract the .tar file in the `data/` folder.
4. Make sure that the folder structure is correct. It should look like the one online and like this (there might be more data but this is not relevant at this point):
```
	MultiplEYE_ZH_CH_Zurich_1_2025/
		documentation/
		eye-tracking-sessions/
			001_.../
			002_.../
			...
			pilot_sessions/
				001_.../
				002_.../
				...
		psychometric-tests-sessions/
		stimuli_MultiplEYE_ZH_CH_Zurich_1_2025/
		...
```

## The config file

The pipeline uses a config file which can be used to specify parameters and settings for the preprocessing. It is typically named `multipleye_settings_preprocessing.yaml`. You can load it explicitly or rely on the default loading mechanism (CWD, environment variable, or legacy root).

Once you have your config file ready, you can load it as shown below.

In [41]:
# from preprocessing.data_collection.multipleye_data_collection import prepare_language_folder
from preprocessing.data_collection.multipleye_data_collection import (
    MultipleyeDataCollection,
)

import preprocessing

# the settings will be loaded into general config module, so we can access all settings at the same place
from preprocessing import settings

from preprocessing.scripts.prepare_language_folder import prepare_language_folder

import polars as pl

from preprocessing.metrics.reading.words import (
    mark_skipped_tokens,
    all_tokens_from_aois,
)

from pymovements.measure.reading.processing import compute_reading_measures

In [2]:
# If you have a specific config file, load it here:
settings.load_from_yaml("multipleye_settings_preprocessing.yaml")

In [3]:
# get the data collection name from the settings and create the path to the data folder
print(f"Active Data Collection: {settings.DATA_COLLECTION_NAME}")
print(f"Dataset Directory: {settings.DATASET_DIR}")

Active Data Collection: MultiplEYE_SV_CH_Zurich_1_2026
Dataset Directory: /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/data/MultiplEYE_SV_CH_Zurich_1_2026

### Inspecting and overriding configuration

After loading the config, you can inspect which sessions are included or excluded, and override these values for the current session without modifying the YAML file.

In [5]:
print(f"Include pilots:  {settings.INCLUDE_PILOTS}")
print(f"Included:        {settings.INCLUDE_SESSIONS}")
print(f"Excluded:        {settings.EXCLUDE_SESSIONS}")
print(f"Output dir:      {settings.OUTPUT_DIR}")
print(f"Run preflight:   {settings.RUN_PREFLIGHT_CHECK}")
print(f"Overwrite:       {settings.OVERWRITE}")

# Override example (uncomment to limit processing to specific sessions):
# settings.INCLUDE_SESSIONS = ["014_DE_DE_1_ET1", "023_DE_DE_1_ET1"]
# settings.EXCLUDE_SESSIONS = []

Include pilots:  True
Included:        ['003_SV_CH_1_ET1']
Excluded:        []
Output dir:      /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026
Run preflight:   True
Overwrite:       True

## MultiplEYE-specific preprocessing & cleaning

In order to be able to run a more generic preprocessing, the MultiplEYE data folder for one language needs to be cleaned and organized in a specific way. Running the script below will:
- unzip session folders if needed
- move session folders from core_sessions folder to the top folder
- check if there is a config file in the stimuli folder (if not, the stimulus folder was probably not uploaded correctly)
- check if there are psychometric tests (if applicable)
	- if necessary, restructure the psychometric test folder.

These steps are very individual for this data collection and results from bugs or changes across the years of collecting data.

Note that executing the cell below for the first time can take very long. However, it will run through quickly after this initial run.

In [6]:
# run the preparation function to prepare the language folder structure
prepare_language_folder()

2026-08-03 08:49:36,034 - preprocessing - INFO - Copying stimulus assets to /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026...

Next, we create a `MultipleyeDataCollection` object from the data folder. This will allow us to easily access the sessions and their information in the next steps.

In [7]:
multipleye = MultipleyeDataCollection.create_from_data_folder(
    settings.DATASET_DIR,
    include_pilots=settings.INCLUDE_PILOTS,
    excluded_sessions=settings.EXCLUDE_SESSIONS,
    included_sessions=settings.INCLUDE_SESSIONS,
)

2026-08-03 08:49:38,157 - preprocessing - INFO - Lab config loaded from /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/config/config_sv_ch_Zurich_1_2026.py
2026-08-03 08:49:38,159 - preprocessing - INFO - JSON lab config loaded from /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/config/MultiplEYE_SV_CH_Zurich_1_2026_lab_configuration.json
2026-08-03 08:49:38,163 - preprocessing - INFO - MultipleyeDataCollection initialized. data_root: /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/data/MultiplEYE_SV_CH_Zurich_1_2026/eye-tracking-sessions
2026-08-03 08:49:38,166 - preprocessing - INFO - Main config loaded from /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/config/config_sv_ch_Zurich_1.py
2026-08-03 08:49:38,169 - preprocessing - WARNING - Folder in eye-tracking-sessions 'tests_sessions' does not match the eye-tracking session regex pattern \d\d\d_SV_CH_1_ET\d(?:_.*)?. Not considered an eye-tracking session.

### Preflight check

Before processing, run a preflight check to validate the dataset structure and catch common issues (missing files, incorrect folder layout, etc.). In case EDF files are missing, you can use `settings.EXCLUDE_SESSIONS = []` to exclude specific sessions, as shown a few cells above.

In [8]:
preprocessing.run_preflight_check(multipleye)

2026-08-03 08:49:41,155 - preprocessing - INFO -
========================================================
  Preflight check — all input files found
========================================================

## Stage 0: Converting EDF to ASC and Preparing Session-Level Information

Stage 0 refers to the initial steps of preprocessing, which involve converting raw eye-tracking data from its original format (e.g., EDF) into a more accessible format (e.g., ASC), and preparing session-level information. This stage is specific to EyeLink eye-trackers and can be omitted for other eye-trackers.

In [9]:
multipleye.convert_edf_to_asc()

2026-08-03 08:49:43,563 - preprocessing - INFO - Starting EDF to ASC conversion for 1 sessions.
Converting EDF to ASC: 100%|██████████| 1/1 [00:00<00:00, 1033.59it/s]
2026-08-03 08:49:43,573 - preprocessing - INFO - EDF to ASC conversion completed.

Once this conversion has been completed, we can load all sessions and parse the .asc files.

In [10]:
multipleye.prepare_session_level_information()

Preparing session 003_SV_CH_1_ET1: 100%|██████████| 1/1 [00:11<00:00, 11.46s/it]

In [11]:
# print an overview on the data collection and the sessions
multipleye

Title	MultiplEYE_SV_CH_Zurich_1_2026
Dataset_type	MultiplEYE
Number_of_sessions	0
Number_of_pilots	1
Tested_language	SV
Country	CH
Year	2026
Number of eye-tracking (ET) sessions per participant	1

## Stage 1: Extracting Gaze Samples

In the first preprocessing stage, we extract gaze samples from the .asc files and create a gaze dataframe for each session. This dataframe contains the raw gaze data, including the x and y coordinates of the gaze, the timestamp. We also save the raw gaze data in a separate file for each session.

The next steps are performed for one session only. It is always possible to loop over all sessions and apply the same preprocessing steps to each of them, but for the sake of clarity and simplicity, we will work with one session as an example.

In [12]:
# pick only one session as an example to work with in the next steps
sessions = list(multipleye)  # list of Session objects
sess = sessions[0]  # a real Session
sid = sess.sid  # get the session ID (Sid) from the Session
sid

Sid(pid='003', lang='SV', country='CH', lab='1', session='ET1', session_id=1, postfix='')

In [13]:
type(sess)

preprocessing.data_collection.session.Session

### Creating Gaze Frame from ASCII File

In [14]:
gaze = preprocessing.load_gaze_data(
    asc_file=sess.asc_path,
    lab_config=sess.lab_config,
    sid=sess.sid,
    trial_cols=settings.TRIAL_COLS,
    messages=settings.ANSWER_MSG_PATTERNS,  # for comprehension questions later - see Stage 4.
)

In [15]:
# save gaze and metadata
preprocessing.save_raw_data(sid, gaze)
preprocessing.save_session_metadata(sid, gaze)

In [16]:
sid.raw_data_dir, sid.metadata_dir

(PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/raw_data/003_SV_CH_1_ET1'),
 PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/metadata/003_SV_CH_1_ET1'))

### Output directory structure

All preprocessed data is organised by data type under `preprocessed_data/<data_collection_name>/`. Each data type folder contains one subfolder per session:

```
preprocessed_data/<dcn>/
├── raw_data/
│   └── <session_save_name>/
├── fixations/
│   └── <session_save_name>/
├── saccades/
│   └── <session_save_name>/
├── scanpaths/
│   └── <session_save_name>/
├── reading_measures/
│   └── <session_save_name>/
├── sanity_checks/
│   └── <session_save_name>/
├── metadata/
│   └── <session_save_name>/
│       ├── gaze_metadata.json
│       ├── experiment.yaml
│       ├── calibrations.tsv
│       ├── calibrations.feather
│       ├── validations.tsv
│       ├── validations.feather
│       └── <session_idf>_overview.yaml
├── participant_data.csv
├── <dcn>_overview.yaml
└── stimuli_<dcn>/
```

The `Sid` object provides convenient properties to access each path:

In [17]:
print(f"Raw data:        {sid.raw_data_dir}")
print(f"Metadata:        {sid.metadata_dir}")
print(f"Fixations:       {sid.fixations_dir}")
print(f"Saccades:        {sid.saccades_dir}")
print(f"Scanpaths:       {sid.scanpaths_dir}")
print(f"Reading measures: {sid.reading_measures_dir}")

Raw data:        /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/raw_data/003_SV_CH_1_ET1
Metadata:        /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/metadata/003_SV_CH_1_ET1
Fixations:       /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/fixations/003_SV_CH_1_ET1
Saccades:        /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/saccades/003_SV_CH_1_ET1
Scanpaths:       /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/scanpaths/003_SV_CH_1_ET1
Reading measures: /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/reading_measures/003_SV_CH_1_ET1

In order to have the metadata which is extracted by pymovements available to create out session overview, we get this information from pymovements and store it in our session object.

In [18]:
sess.pm_gaze_metadata = gaze._metadata
sess.calibrations = gaze.calibrations
sess.validations = gaze.validations

### Coordinate and Velocity Preprocessing

Eye movements are recorded in screen pixel coordinates, which depend on stimulus size and monitor setup. To compare gaze behavior across participants, screens, or datasets, it is standard to convert pixel positions 
into **degrees of visual angle (dva)**. Next, we compute **gaze velocity**, which allows us to detect saccades and distinguish them from fixations.

In [19]:
# inspect the gaze samples
gaze.samples.head()

shape: (5, 9)
┌─────────┬───────┬────────┬───────────────┬───┬──────────┬──────────┬──────────────┬──────────────┐
│ time    ┆ pupil ┆ page   ┆ stimulus      ┆ … ┆ practice ┆ activity ┆ session      ┆ pixel        │
│ ---     ┆ ---   ┆ ---    ┆ ---           ┆   ┆ ---      ┆ ---      ┆ ---          ┆ ---          │
│ i64     ┆ f64   ┆ str    ┆ str           ┆   ┆ bool     ┆ str      ┆ str          ┆ list[f64]    │
╞═════════╪═══════╪════════╪═══════════════╪═══╪══════════╪══════════╪══════════════╪══════════════╡
│ 2787713 ┆ 799.0 ┆ page_1 ┆ Enc_WikiMoon_ ┆ … ┆ true     ┆ reading  ┆ 003_SV_CH_1_ ┆ [78.9, 93.2] │
│         ┆       ┆        ┆ 13            ┆   ┆          ┆          ┆ ET1          ┆              │
│ 2787714 ┆ 802.0 ┆ page_1 ┆ Enc_WikiMoon_ ┆ … ┆ true     ┆ reading  ┆ 003_SV_CH_1_ ┆ [78.7, 93.3] │
│         ┆       ┆        ┆ 13            ┆   ┆          ┆          ┆ ET1          ┆              │
│ 2787715 ┆ 804.0 ┆ page_1 ┆ Enc_WikiMoon_ ┆ … ┆ true     ┆ reading  ┆ 003_SV_CH_1_ ┆ [79.2, 93.3] │
│         ┆       ┆        ┆ 13            ┆   ┆          ┆          ┆ ET1          ┆              │
│ 2787716 ┆ 801.0 ┆ page_1 ┆ Enc_WikiMoon_ ┆ … ┆ true     ┆ reading  ┆ 003_SV_CH_1_ ┆ [79.9, 91.8] │
│         ┆       ┆        ┆ 13            ┆   ┆          ┆          ┆ ET1          ┆              │
│ 2787717 ┆ 807.0 ┆ page_1 ┆ Enc_WikiMoon_ ┆ … ┆ true     ┆ reading  ┆ 003_SV_CH_1_ ┆ [79.5, 92.3] │
│         ┆       ┆        ┆ 13            ┆   ┆          ┆          ┆ ET1          ┆              │
└─────────┴───────┴────────┴───────────────┴───┴──────────┴──────────┴──────────────┴──────────────┘

In [20]:
preprocessing.preprocess_gaze(gaze)

In [21]:
# inspect the preprocessed gaze samples, the dataframe should now also contain a position in dva and velocity columns
gaze.samples.head()

shape: (5, 11)
┌─────────┬───────┬────────┬─────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ time    ┆ pupil ┆ page   ┆ stimulus    ┆ … ┆ session     ┆ pixel       ┆ position   ┆ velocity   │
│ ---     ┆ ---   ┆ ---    ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ i64     ┆ f64   ┆ str    ┆ str         ┆   ┆ str         ┆ list[f64]   ┆ list[f64]  ┆ list[f64]  │
╞═════════╪═══════╪════════╪═════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 2787713 ┆ 799.0 ┆ page_1 ┆ Enc_WikiMoo ┆ … ┆ 003_SV_CH_1 ┆ [78.9,      ┆ [-15.15147 ┆ [-0.962259 │
│         ┆       ┆        ┆ n_13        ┆   ┆ _ET1        ┆ 93.2]       ┆ 5, -10.741 ┆ ,          │
│         ┆       ┆        ┆             ┆   ┆             ┆             ┆ 041]       ┆ -3.001021] │
│ 2787714 ┆ 802.0 ┆ page_1 ┆ Enc_WikiMoo ┆ … ┆ 003_SV_CH_1 ┆ [78.7,      ┆ [-15.15652 ┆ [-0.925034 │
│         ┆       ┆        ┆ n_13        ┆   ┆ _ET1        ┆ 93.3]       ┆ 4, -10.738 ┆ ,          │
│         ┆       ┆        ┆             ┆   ┆             ┆             ┆ 466]       ┆ -3.194814] │
│ 2787715 ┆ 804.0 ┆ page_1 ┆ Enc_WikiMoo ┆ … ┆ 003_SV_CH_1 ┆ [79.2,      ┆ [-15.14390 ┆ [-0.807383 │
│         ┆       ┆        ┆ n_13        ┆   ┆ _ET1        ┆ 93.3]       ┆ 2, -10.738 ┆ ,          │
│         ┆       ┆        ┆             ┆   ┆             ┆             ┆ 466]       ┆ -3.420028] │
│ 2787716 ┆ 801.0 ┆ page_1 ┆ Enc_WikiMoo ┆ … ┆ 003_SV_CH_1 ┆ [79.9,      ┆ [-15.12622 ┆ [-0.721037 │
│         ┆       ┆        ┆ n_13        ┆   ┆ _ET1        ┆ 91.8]       ┆ 8, -10.777 ┆ ,          │
│         ┆       ┆        ┆             ┆   ┆             ┆             ┆ 098]       ┆ -3.634057] │
│ 2787717 ┆ 807.0 ┆ page_1 ┆ Enc_WikiMoo ┆ … ┆ 003_SV_CH_1 ┆ [79.5,      ┆ [-15.13632 ┆ [-0.624866 │
│         ┆       ┆        ┆ n_13        ┆   ┆ _ET1        ┆ 92.3]       ┆ 8, -10.764 ┆ ,          │
│         ┆       ┆        ┆             ┆   ┆             ┆             ┆ 222]       ┆ -3.77264]  │
└─────────┴───────┴────────┴─────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

## Stage 2a: Detect Events and Compute Their Properties

Eye-tracking data are typically segmented into events, i.e. `fixations` and `saccades`. Fixations represent moments when the eyes remain relatively still, allowing visual information to be processed, while saccades are the rapid movements between fixations that reposition the gaze. Detecting these events and computing their properties, such as `dispersion`, fixation `duration`, saccade `amplitude`, and `peak velocity`, provides the foundation for analyzing visual behavior and understanding how participants explore a stimulus.

### Fixations

We can detect fixations by applying the `I-VT` or the `I-DT` method.

The **I-VT (Velocity-Threshold Identification)** method distinguishes fixation and saccade points based on their point-to-point velocities. Each point is classified as a fixation if its velocity is below the specified threshold. Consecutive fixation points are then merged into a single fixation. A threshold of 20 degrees/second is commonly used as a default maximum value. Read more about [the IVT algorithm in the documentation](https://pymovements.readthedocs.io/en/stable/reference/api/pymovements.events.detection.ivt.html) 

The **I-DT (Dispersion-Threshold Identification)** method finds fixations by grouping consecutive points within a maximum separation (dispersion) threshold and a minimum duration threshold. The algorithm slides a moving window across the data: if the dispersion within the window is below the threshold, the window represents a fixation and is gradually expanded until the dispersion exceeds the threshold.
Read more about [our implementation of the IDT method](https://pymovements.readthedocs.io/en/stable/reference/api/pymovements.events.detection.idt.html).

We use the `I-VT` algorithm with the following key deafault parameters:
- `minimum duration`: 100 ms 
- `velocity threshold`: 20.0

Such properties as `location`, containing the centroid coordinates of each fixation, and `dispersion` will also be calculated.

In [22]:
preprocessing.detect_fixations(
    gaze,
)

### Saccades

Saccades are rapid eye movements that shift the point of fixation from one location to another. We detect saccades (or micro-saccades) from the velocity sequence of gaze data using the [microsaccades algorithm](https://pymovements.readthedocs.io/en/stable/reference/api/pymovements.events.detection.microsaccades.html#pymovements.events.detection.microsaccades). This algorithm implements a noise-adaptive velocity threshold, meaning that the detection threshold automatically scales with the noise level of the velocity signal. Such properties as `amplitude` and `peak velocity` of the detected saccades will also be calcuated.

The key default parameters are:
- `threshold_factor`: Multiplier used to determine the velocity threshold relative to the noise level of the signal. The default value is 6. A higher factor makes the algorithm more conservative (detects fewer saccades), while a lower factor makes it more sensitive.
- `minimum_duration`: Defines how long a velocity peak must persist to be classified as a saccade. The duration is expressed in the same units as timesteps. If no timesteps are provided, the value refers to the number of samples (default = 6), which corresponds to about 12 ms at a 500 Hz sampling rate. Shorter events are ignored as noise.

In [23]:
preprocessing.detect_saccades(
    gaze,
)

Save our events data.

In [24]:
preprocessing.save_events_data(
    settings.FIXATION,
    sess.sid,
    split_column="trial",
    name_columns=["trial", "stimulus"],
    file_columns=["onset", "duration", "location_x", "location_y", "page"],
    data=gaze,
)

preprocessing.save_events_data(
    settings.SACCADE,
    sess.sid,
    split_column="trial",
    name_columns=["trial", "stimulus"],
    file_columns=[
        "onset",
        "duration",
        "amplitude",
        "peak_velocity",
        "dispersion",
        "page",
    ],
    data=gaze,
)

In [25]:
str(sess.sid), sess.sid

('003_SV_CH_1_ET1',
 Sid(pid='003', lang='SV', country='CH', lab='1', session='ET1', session_id=1, postfix=''))

In [26]:
sess.stimuli

[Stimulus(id=1, name='PopSci_MultiplEYE', type='experiment', pages=[StimulusPage(number=1, text='MultiplEYE-projektet\n\nNamnet ”MultiplEYE” är en ordlek som kombinerar ”multilingualism” eller ”multiple languages” med ”eye” från ”eye-tracking”. MultiplEYE är en COST-aktion finansierad av den Europeiska unionen. COST-aktioner är forskningsnätverk som stöds av European Cooperation in Science and Technology, förkortat COST. Som finansiär stöder COST vårt växande nätverk av forskare i och utanför Europa genom att ge ekonomiskt stöd till genomförandet av olika networkingevent.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_1_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_1_sv_aoi.png')), StimulusPage(number=2, text='Dessa event omfattar möten i arbetsgrupper, träningskurser för att dela kunskaper med yngre forskare och vetenskapliga forskningsutbyten. Projekttiteln för COST-aktionen MultiplEYE är: Möjliggörande av insamling av flerspråkig eye-trackingdata för forskning på mänsklig och maskinell språkbehandling. Med det menas att syftet för COST-aktionen MultiplEYE är att främja ett interdisciplinärt forskningsnätverk som arbetar med att samla in eye-trackingdata från läsning på flera språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_2_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_2_sv_aoi.png')), StimulusPage(number=3, text='Målet är att stödja utvecklingen av en stor flerspråkig eye-trackingkorpus och göra det möjligt för forskare att samla in data genom att dela med sig av sina kunskaper mellan olika fält, däribland lingvistik, psykologi, tal- och språkpatologi och datavetenskap. Datasamlingen kan sedan användas för att studera mänsklig språkbehandling från ett psykolingvistiskt perspektiv samt för att förbättra och utvärdera maskinell språkbehandling från ett maskininlärningsperspektiv.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_3_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_3_sv_aoi.png')), StimulusPage(number=4, text='Vad är ”eye-tracking”?\nEye-tracking är en metod där man mäter blickpunkten, det vill säga var du tittar, och ögonens rörelser mellan fasta blickpunkter. Den apparat som används för att mäta ögonens position och rörelser kallas eye-tracker. Den består av en infraröd kamera med en ljusfrekvens som varken påverkar eller skadar människoögat.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_4_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_4_sv_aoi.png')), StimulusPage(number=5, text='Med hjälp av algoritmer för bildigenkänning kan eye-trackern med stor precision uppskatta blickpunkterna genom att registrera huvudets och ögonens position, avståndet till den skärm deltagaren tittar på och eye-trackerns position. Eye-tracking är en användbar teknik inom många områden. Den kan till exempel användas för att upptäcka trötthet under bilkörning, eller för att stödja applikationer för screening eller utbildning inom det medicinska området. Eye-tracking används också inom datorspel, marknadsföring och människa-datorinteraktion.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_5_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_5_sv_aoi.png')), StimulusPage(number=6, text='Varför är eye-tracking under läsning särskilt intressant för vårt projekt?\nMedan du läser de här orden följer eye-trackern dina ögonrörelser över texten. Detta ger information om hur lång tid du tittar på en text, eller mer specifikt, hur lång du tittar på varje ord, vilka ord du hoppar över, vilka ord du dröjer vid, och om du behöver gå tillbaka och läsa om delar av texten för att förstå den bättre. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_6_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_6_sv_aoi.png')), StimulusPage(number=7, text='När din hjärna bearbetar textens innehåll återspeglar dina ögonrörelser, nästan i realtid, mycket av den språkliga och kognitiva bearbetning som pågår. Den registrerade datan är således en guldgruva av information om hur vi sätter samman en texts betydelse och grammatiska struktur. Den visar vilka delar av texten som är utmanande och vilka delar som är lättlästa. Efteråt är det upp till forskarna att förklara vilka språkliga faktorer som orsakar vilken typ av ögonrörelser.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_7_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_7_sv_aoi.png')), StimulusPage(number=8, text='Motivationen bakom MultiplEYE är att det fortfarande finns för lite eye-trackingdata, särskilt från språk med färre talare. En datainsamling av denna omfattning är en utmaning när det gäller att utveckla och komma överens om experimentets design, komplexitet och vilka sorters texter som ska läsas av deltagarna. Andra beslut som kan tyckas vara mindre relevanta, men som egentligen är av stor vikt innefattar textstorlek och typsnitt, i vilken ordning texterna presenteras, experimentets genomförande och hur data bearbetas.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_8_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_8_sv_aoi.png')), StimulusPage(number=9, text='När det väl är klart kommer datasamlingen att ge oss möjligheten att undersöka många ämnen kopplade till psykolingvistik och datalingvistik. Till exempel kan vi jämföra läsbeteenden mellan olika språk. Påverkar skriften, till exempel det latinska alfabetet jämfört med kyrilliska eller arabiska alfabet, lästiden? Ett exempel på maskinell behandling av text skulle kunna vara att använda eye-trackingdata i utvecklingen av program baserade på artificiell intelligens som imiterar den mänskliga läsprocessen. Detta skulle kunna användas för att bygga bättre maskinöversättningssystem eller för att förbättra den automatiska extraktionen av nyckelord från en text.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_9_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_9_sv_aoi.png')), StimulusPage(number=10, text='Att få eye-trackingdata från många deltagare, inklusive dig själv, som läser texter på en rad olika språk kommer att utgöra en bra grund för vår forskning. Det kommer att vara den viktigaste faktorn för att göra vårt forskningsnätverk framgångsrikt. Vi hoppas kunna bana väg för forskningsframsteg i en rad av lingvistikens underordnade fält genom att föra samman och stödja en stor grupp av forskare.\n', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_10_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_10_sv_aoi.png')), StimulusPage(number=11, text='De viktigaste resultaten från MultiplEYE-projektet kommer att vara ett stort dataset med eye-trackingdata på många språk och en plattform för nya samarbeten som bygger på denna typ av data. Om du läser denna text stödjer du redan vårt arbete genom att låta oss samla in och analysera dina ögonrörelser medan du läser och förstår språk. Tack!', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_11_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_11_sv_aoi.png'))], text_stimulus=<pymovements.stimulus.text.TextStimulus object at 0x7f6d619f02f0>, questions=[ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01111', id='01111', snippet_no=1, question='Vad är en COST-aktion?', target='Det är ett forskningsnätverk som finansieras av den Europeiska unionen.', distractor_a='Det är ett europeiskt forskningsnätverk för tekniska innovationer.', distractor_b='Det är ett forskningsnätverk för eye-tracking på flera språk. ', distractor_c='Det är ett europeiskt nätverk för forskning i läsning på flera språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01111_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01111_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01112', id='01112', snippet_no=1, question='Vad använder medlemmarna i MultiplEYE-projektet en eye-tracker till?', target='Att mäta blickpunkten och ögonens rörelser.', distractor_a='Att mäta huvudets riktning och rörelse under läsning.', distractor_b='Att mäta en texts betydelse och grammatiska struktur. ', distractor_c='Att mäta tanklös läsning av text och hur det påverkar förståelsen. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01112_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01112_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01121', id='01121', snippet_no=1, question='Varför är eye-tracking användbart för att studera språk inom ramen för projektet?', target='Eye-tracking används för att dra slutsatser om hur människor förstår text när de läser.', distractor_a='Eye-tracking används för att identifiera grammatiska fel i texten.', distractor_b='Eye-tracking används för att undersöka likheterna mellan läsning av texter i olika skrifter.', distractor_c='Eye-tracking används för att förstå vad språk betyder för människor. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01121_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01121_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01122', id='01122', snippet_no=1, question='Vad är det övergripande målet för forskarna i MultiplEYE-projektet?', target='Att samla in eye-trackingdata för att främja tvärvetenskaplig forskning i läsning.', distractor_a='Att samla in texter för att främja forskning inom många språkvetenskapliga områden.', distractor_b='Att samla in en ögonrörelsekorpus för att jämföra texter med olika typsnitt och teckenstorlek.', distractor_c='Att samla in eye-trackingdata för att kunna förstå hur människor lär sig nya språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01122_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01122_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01131', id='01131', snippet_no=1, question='Vad är en stor utmaning för MultiplEYE-projektet?', target='Att se till att deltagarna läser bra översättningar av texterna på sina respektive språk.', distractor_a='Att få finansiering till nätverksaktiviteter och forskningsbesök.', distractor_b='Att få ut blickpunkter och deltagarens avstånd till eye-trackern.', distractor_c='Att hantera etiska överväganden kopplade till datasekretess.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01131_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01131_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01132', id='01132', snippet_no=1, question='Vilken information förmedlas i texten?', target='Projektets huvudfokus och infrastruktur för samarbete. ', distractor_a='Mekaniken bakom mänskliga ögonrörelser.', distractor_b='Metoder för att extrahera information från text.', distractor_c='Reglerna för projekt inom ramen för European Cooperation in Science and Technology.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01132_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01132_sv_aoi.png'))], instructions=[Instruction(id=1, name='welcome_screen', text='Välkommen till MultiplEYE-studien\n\n\n\nNär du är redo, tryck på mellanslagstangenten för att komma till instruktionerna.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/welcome_screen_sv.png')), Instruction(id=2, name='empty_screen', text=None, image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/empty_screen_sv.png')), Instruction(id=3, name='fixation_screen', text=None, image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/fixation_screen_sv.png')), Instruction(id=4, name='obligatory_break_screen', text='Du ska nu ta en paus på 5 minuter. Du får gärna ställa dig upp, röra huvudet, låta ögonen slappna av och dricka lite vatten. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/obligatory_break_screen_sv.png')), Instruction(id=5, name='optional_break_screen', text='Du kan nu ta en paus eller ta lite vatten, eller så trycker du på mellanslagstangenten för att fortsätta läsa. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/optional_break_screen_sv.png')), Instruction(id=6, name='final_screen', text='Tack så mycket för din medverkan!\n\nHejdå!', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/final_screen_sv.png')), Instruction(id=7, name='practice_screen', text='Vi kommer nu att inleda med två övningstexter för att du ska få en förståelse för hur experimentet genomförs. Om något är oklart eller om du har frågor kan du prata med försöksledaren.\n\nVänligen titta på den svarta pricken längst ned i det högra hörnet och tryck sedan på mellanslagstangenten för att börja med övningstexterna. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/practice_screen_sv.png')), Instruction(id=8, name='transition_screen', text='\nDu är nu klar med övningstexterna. Experimentet inleds när du är redo. Försök att röra dig så lite som möjligt när du läser texterna. Rör du dig för mycket kan vi behöva omkalibr

## Stage 2b: Map Fixations to AOIs

Once we have the fixations, we can map each of them to the AOIs of the stimulus. The resulting scanpath can then be saved. Note that this features is not yet completely finished.

In [27]:
preprocessing.map_fixations_to_aois(gaze, sess.stimuli)

In [28]:
gaze.events.frame

shape: (24_011, 24)
┌────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ trial      ┆ stimulus   ┆ page      ┆ name     ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_ ┆ word      │
│ ---        ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ in_line   ┆ ---       │
│ str        ┆ str        ┆ str       ┆ str      ┆   ┆ i64      ┆ i64      ┆ ---       ┆ str       │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ i64       ┆           │
╞════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ PRACTICE_t ┆ Enc_WikiMo ┆ page_1    ┆ fixation ┆ … ┆ null     ┆ null     ┆ null      ┆ null      │
│ rial_1     ┆ on_13      ┆           ┆          ┆   ┆          ┆          ┆           ┆           │
│ PRACTICE_t ┆ Enc_WikiMo ┆ page_1    ┆ fixation ┆ … ┆ 0        ┆ 0        ┆ 0         ┆ Månen     │
│ rial_1     ┆ on_13      ┆           ┆          ┆   ┆          ┆          ┆           ┆           │
│ PRACTICE_t ┆ Enc_WikiMo ┆ page_1    ┆ fixation ┆ … ┆ 1        ┆ 1        ┆ 0         ┆ https://e │
│ rial_1     ┆ on_13      ┆           ┆          ┆   ┆          ┆          ┆           ┆ n.wikiped │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆           ┆ ia.org/wi │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆           ┆ ki/…      │
│ PRACTICE_t ┆ Enc_WikiMo ┆ page_1    ┆ fixation ┆ … ┆ 0        ┆ 0        ┆ 0         ┆ Månen     │
│ rial_1     ┆ on_13      ┆           ┆          ┆   ┆          ┆          ┆           ┆           │
│ PRACTICE_t ┆ Enc_WikiMo ┆ page_1    ┆ fixation ┆ … ┆ 1        ┆ 1        ┆ 0         ┆ https://e │
│ rial_1     ┆ on_13      ┆           ┆          ┆   ┆          ┆          ┆           ┆ n.wikiped │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆           ┆ ia.org/wi │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆           ┆ ki/…      │
│ …          ┆ …          ┆ …         ┆ …        ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ trial_10   ┆ PopSci_Mul ┆ question_ ┆ saccade  ┆ … ┆ null     ┆ null     ┆ null      ┆ null      │
│            ┆ tiplEYE_1  ┆ 1132      ┆          ┆   ┆          ┆          ┆           ┆           │
│ trial_10   ┆ PopSci_Mul ┆ question_ ┆ saccade  ┆ … ┆ null     ┆ null     ┆ null      ┆ null      │
│            ┆ tiplEYE_1  ┆ 1132      ┆          ┆   ┆          ┆          ┆           ┆           │
│ trial_10   ┆ PopSci_Mul ┆ question_ ┆ saccade  ┆ … ┆ null     ┆ null     ┆ null      ┆ null      │
│            ┆ tiplEYE_1  ┆ 1132      ┆          ┆   ┆          ┆          ┆           ┆           │
│ trial_10   ┆ PopSci_Mul ┆ question_ ┆ saccade  ┆ … ┆ null     ┆ null     ┆ null      ┆ null      │
│            ┆ tiplEYE_1  ┆ 1132      ┆          ┆   ┆          ┆          ┆           ┆           │
│ trial_10   ┆ PopSci_Mul ┆ question_ ┆ saccade  ┆ … ┆ null     ┆ null     ┆ null      ┆ null      │
│            ┆ tiplEYE_1  ┆ 1132      ┆          ┆   ┆          ┆          ┆           ┆           │
└────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴───────────┴───────────┘

### New Method

Taken from the annotate fixations method in fixations.py

In [29]:

group_columns = [settings.TRIAL_COL, settings.STIMULUS_COL, settings.PAGE_COL]

only_fix = (
        gaze.events.frame.filter(
            (pl.col("name") == settings.FIXATION)
            & (pl.col(settings.WORD_IDX_COL).is_not_null())
        )
        .with_row_count("fixation_id")
        .sort(group_columns + ["onset"])
    )

2026-08-03 09:16:13,441 - py.warnings - PYWARN:WARNING - /tmp/ipykernel_8363/944958957.py:8: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  .with_row_count("fixation_id")

In [30]:
only_fix

shape: (6_520, 25)
┌────────────┬────────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ fixation_i ┆ trial      ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word      │
│ d          ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str       │
│ u32        ┆            ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ 0          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Månen     │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆           │
│ 1          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 1        ┆ 1        ┆ 0          ┆ https://e │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆ n.wikiped │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ia.org/wi │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ki/…      │
│ 2          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Månen     │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆           │
│ 3          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 1        ┆ 1        ┆ 0          ┆ https://e │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆ n.wikiped │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ia.org/wi │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ki/…      │
│ 4          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 1        ┆ 1        ┆ 0          ┆ https://e │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆ n.wikiped │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ia.org/wi │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ki/…      │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ 5930       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 3        ┆ 57       ┆ 10         ┆ Guds      │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
│ 5931       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 3        ┆ 58       ┆ 11         ┆ namn      │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
│ 5932       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 3        ┆ 59       ┆ 12         ┆ ändå      │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
│ 5933       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 3        ┆ 61       ┆ 14         ┆ bli       │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
│ 5934       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 4        ┆ 63       ┆ 0          ┆ år!       │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
└────────────┴────────────┴────────────┴────────┴───┴──────────┴──────────┴────────────┴───────────┘

In [31]:
stim = sess.stimuli[2]
aois = stim.text_stimulus.aois
words_only = all_tokens_from_aois(aois, trial=stim.trial_id)
words_only = words_only.with_columns(pl.lit(stim.name).alias("stimulus"))
words_only = words_only.filter(pl.col("page")=="page_2")
words_only

shape: (63, 5)
┌─────────┬────────┬──────────┬─────────────┬──────────────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word        ┆ stimulus             │
│ ---     ┆ ---    ┆ ---      ┆ ---         ┆ ---                  │
│ str     ┆ str    ┆ i64      ┆ str         ┆ str                  │
╞═════════╪════════╪══════════╪═════════════╪══════════════════════╡
│ trial_5 ┆ page_2 ┆ 0        ┆ Utbildning, ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 1        ┆ studier     ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 2        ┆ och         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 3        ┆ praktik     ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 4        ┆ i           ┆ Ins_LearningMobility │
│ …       ┆ …      ┆ …        ┆ …           ┆ …                    │
│ trial_5 ┆ page_2 ┆ 58       ┆ och         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 59       ┆ stöd        ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 60       ┆ via         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 61       ┆ programmet  ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 62       ┆ Erasmus+.   ┆ Ins_LearningMobility │
└─────────┴────────┴──────────┴─────────────┴──────────────────────┘

In [32]:
only_fix = only_fix.filter((pl.col("trial")=="trial_5") & (pl.col("page")=="page_2"))
only_fix

shape: (64, 25)
┌─────────────┬─────────┬─────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial   ┆ stimulus    ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---     ┆ ---         ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str     ┆ str         ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆         ┆             ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪═════════╪═════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 3161        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Utbildning │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆ ,          │
│ 3162        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ studier    │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 3163        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ studier    │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 3164        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 3        ┆ 3          ┆ praktik    │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 3165        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ ett        │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ …           ┆ …       ┆ …           ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 3220        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 6        ┆ 62       ┆ 1          ┆ Erasmus+.  │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 3221        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 5        ┆ 55       ┆ 8          ┆ ett        │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 3222        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 5        ┆ 56       ┆ 9          ┆ särskilt   │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 3223        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 5        ┆ 57       ┆ 10         ┆ riktmärke  │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 3224        ┆ trial_5 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 5        ┆ 59       ┆ 12         ┆ stöd       │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
└─────────────┴─────────┴─────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘

In [33]:
rm_df = compute_reading_measures(
    fixations=only_fix,
    aois = words_only,
    word_index_column= "word_idx",
    word_column = "word"
)

In [102]:
rm_df

shape: (62, 21)
┌────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word       ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---        ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str        ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ studier    ┆ 0          ┆ 157 ┆ 0   ┆ … ┆ 0      ┆ 1     ┆ 2      ┆ 2   │
│ och        ┆ 1          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ praktik    ┆ 2          ┆ 172 ┆ 172 ┆ … ┆ 0      ┆ 2     ┆ 2      ┆ 1   │
│ i          ┆ 3          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ ett        ┆ 4          ┆ 139 ┆ 139 ┆ … ┆ 0      ┆ 2     ┆ 3      ┆ 1   │
│ …          ┆ …          ┆ …   ┆ …   ┆ … ┆ …      ┆ …     ┆ …      ┆ …   │
│ och        ┆ 57         ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ stöd       ┆ 58         ┆ 141 ┆ 141 ┆ … ┆ 0      ┆ 2     ┆ 2      ┆ 2   │
│ via        ┆ 59         ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ programmet ┆ 60         ┆ 167 ┆ 167 ┆ … ┆ 0      ┆ 2     ┆ 1      ┆ 1   │
│ Erasmus+.  ┆ 61         ┆ 234 ┆ 234 ┆ … ┆ 0      ┆ 1     ┆ -7     ┆ 1   │
└────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘

## Old Method

In [37]:
# The resulting mapping can be stored as a scanpath, which is a sequence of AOIs that were fixated in the order they were fixated.
preprocessing.save_scanpaths(sid, gaze)

In [38]:
# save metadata again
preprocessing.save_session_metadata(sid, gaze)

In [39]:
old_rm_df = preprocessing.calculate_reading_measures(gaze, sess.stimuli)
preprocessing.save_reading_measures(sid, old_rm_df)

In [42]:
new_rm_df = preprocessing.new_calculate_reading_measures(gaze, sess.stimuli)
preprocessing.save_reading_measures(sid, new_rm_df)

AttributeError: module 'preprocessing' has no attribute 'new_calculate_reading_measures'

In [40]:
old_rm_df.filter((pl.col("trial") == "trial_10") & (pl.col("page")=="page_1"))

shape: (62, 25)
┌──────────┬────────┬──────────┬──────────────────────┬───┬──────┬─────┬─────┬─────┐
│ trial    ┆ page   ┆ word_idx ┆ word                 ┆ … ┆ TFT  ┆ FPF ┆ RR  ┆ SFD │
│ ---      ┆ ---    ┆ ---      ┆ ---                  ┆   ┆ ---  ┆ --- ┆ --- ┆ --- │
│ str      ┆ str    ┆ i64      ┆ str                  ┆   ┆ i64  ┆ i8  ┆ i8  ┆ i64 │
╞══════════╪════════╪══════════╪══════════════════════╪═══╪══════╪═════╪═════╪═════╡
│ trial_10 ┆ page_1 ┆ 0        ┆ MultiplEYE-projektet ┆ … ┆ 337  ┆ 1   ┆ 0   ┆ 0   │
│ trial_10 ┆ page_1 ┆ 1        ┆ Namnet               ┆ … ┆ 155  ┆ 1   ┆ 0   ┆ 155 │
│ trial_10 ┆ page_1 ┆ 2        ┆ ”MultiplEYE”         ┆ … ┆ 2519 ┆ 1   ┆ 1   ┆ 0   │
│ trial_10 ┆ page_1 ┆ 3        ┆ är                   ┆ … ┆ 0    ┆ 0   ┆ 0   ┆ 0   │
│ trial_10 ┆ page_1 ┆ 4        ┆ en                   ┆ … ┆ 140  ┆ 0   ┆ 1   ┆ 0   │
│ …        ┆ …      ┆ …        ┆ …                    ┆ … ┆ …    ┆ …   ┆ …   ┆ …   │
│ trial_10 ┆ page_1 ┆ 57       ┆ till                 ┆ … ┆ 0    ┆ 0   ┆ 0   ┆ 0   │
│ trial_10 ┆ page_1 ┆ 58       ┆ genomförandet        ┆ … ┆ 142  ┆ 1   ┆ 0   ┆ 142 │
│ trial_10 ┆ page_1 ┆ 59       ┆ av                   ┆ … ┆ 0    ┆ 0   ┆ 0   ┆ 0   │
│ trial_10 ┆ page_1 ┆ 60       ┆ olika                ┆ … ┆ 154  ┆ 1   ┆ 0   ┆ 154 │
│ trial_10 ┆ page_1 ┆ 61       ┆ networkingevent.     ┆ … ┆ 220  ┆ 1   ┆ 0   ┆ 220 │
└──────────┴────────┴──────────┴──────────────────────┴───┴──────┴─────┴─────┴─────┘

## Pymovements weirdness

In [106]:
fixations = only_fix
aois = words_only
word_index_column= "word_idx"
word_column = "word"

In [107]:
fixations

shape: (64, 25)
┌────────────┬─────────┬────────────┬────────┬───┬────────────┬───────────┬────────────┬───────────┐
│ fixation_i ┆ trial   ┆ stimulus   ┆ page   ┆ … ┆ word       ┆ amplitude ┆ peak_veloc ┆ dispersio │
│ d          ┆ ---     ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---       ┆ ity        ┆ n_right   │
│ ---        ┆ str     ┆ str        ┆ str    ┆   ┆ str        ┆ f64       ┆ ---        ┆ ---       │
│ u32        ┆         ┆            ┆        ┆   ┆            ┆           ┆ f64        ┆ f64       │
╞════════════╪═════════╪════════════╪════════╪═══╪════════════╪═══════════╪════════════╪═══════════╡
│ 3161       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ Utbildning ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆ ,          ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3162       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ studier    ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3163       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ studier    ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3164       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ praktik    ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3165       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ ett        ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ …          ┆ …       ┆ …          ┆ …      ┆ … ┆ …          ┆ …         ┆ …          ┆ …         │
│ 3220       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ Erasmus+.  ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3221       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ ett        ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3222       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ särskilt   ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3223       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ riktmärke  ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3224       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ stöd       ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
└────────────┴─────────┴────────────┴────────┴───┴────────────┴───────────┴────────────┴───────────┘

In [108]:
dummy_fixation_dict: dict[str, list[int] | list[str]] = {}
for col, dtype in fixations.schema.items():
    if dtype == pl.String:
        dummy_fixation_dict[col] = ['']
    else:
        dummy_fixation_dict[col] = [0]
dummy_fixation = pl.DataFrame(
    dummy_fixation_dict,
    schema=fixations.schema,
)
fixations = pl.concat([fixations, dummy_fixation])

In [109]:
fixations

shape: (65, 25)
┌────────────┬─────────┬────────────┬────────┬───┬────────────┬───────────┬────────────┬───────────┐
│ fixation_i ┆ trial   ┆ stimulus   ┆ page   ┆ … ┆ word       ┆ amplitude ┆ peak_veloc ┆ dispersio │
│ d          ┆ ---     ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---       ┆ ity        ┆ n_right   │
│ ---        ┆ str     ┆ str        ┆ str    ┆   ┆ str        ┆ f64       ┆ ---        ┆ ---       │
│ u32        ┆         ┆            ┆        ┆   ┆            ┆           ┆ f64        ┆ f64       │
╞════════════╪═════════╪════════════╪════════╪═══╪════════════╪═══════════╪════════════╪═══════════╡
│ 3161       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ Utbildning ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆ ,          ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3162       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ studier    ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3163       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ studier    ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3164       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ praktik    ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3165       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ ett        ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ …          ┆ …       ┆ …          ┆ …      ┆ … ┆ …          ┆ …         ┆ …          ┆ …         │
│ 3221       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ ett        ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3222       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ särskilt   ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3223       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ riktmärke  ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 3224       ┆ trial_5 ┆ Ins_Learni ┆ page_2 ┆ … ┆ stöd       ┆ null      ┆ null       ┆ null      │
│            ┆         ┆ ngMobility ┆        ┆   ┆            ┆           ┆            ┆           │
│            ┆         ┆ _3         ┆        ┆   ┆            ┆           ┆            ┆           │
│ 0          ┆         ┆            ┆        ┆ … ┆            ┆ 0.0       ┆ 0.0        ┆ 0.0       │
└────────────┴─────────┴────────────┴────────┴───┴────────────┴───────────┴────────────┴───────────┘

In [111]:
words_only

shape: (63, 5)
┌─────────┬────────┬──────────┬─────────────┬──────────────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word        ┆ stimulus             │
│ ---     ┆ ---    ┆ ---      ┆ ---         ┆ ---                  │
│ str     ┆ str    ┆ i64      ┆ str         ┆ str                  │
╞═════════╪════════╪══════════╪═════════════╪══════════════════════╡
│ trial_5 ┆ page_2 ┆ 0        ┆ Utbildning, ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 1        ┆ studier     ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 2        ┆ och         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 3        ┆ praktik     ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 4        ┆ i           ┆ Ins_LearningMobility │
│ …       ┆ …      ┆ …        ┆ …           ┆ …                    │
│ trial_5 ┆ page_2 ┆ 58       ┆ och         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 59       ┆ stöd        ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 60       ┆ via         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 61       ┆ programmet  ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 62       ┆ Erasmus+.   ┆ Ins_LearningMobility │
└─────────┴────────┴──────────┴─────────────┴──────────────────────┘

In [110]:
aois = aois.with_columns(
        (pl.col(word_index_column) - 1).alias(word_index_column),
    )
aois

shape: (63, 5)
┌─────────┬────────┬──────────┬─────────────┬──────────────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word        ┆ stimulus             │
│ ---     ┆ ---    ┆ ---      ┆ ---         ┆ ---                  │
│ str     ┆ str    ┆ i64      ┆ str         ┆ str                  │
╞═════════╪════════╪══════════╪═════════════╪══════════════════════╡
│ trial_5 ┆ page_2 ┆ -1       ┆ Utbildning, ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 0        ┆ studier     ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 1        ┆ och         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 2        ┆ praktik     ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 3        ┆ i           ┆ Ins_LearningMobility │
│ …       ┆ …      ┆ …        ┆ …           ┆ …                    │
│ trial_5 ┆ page_2 ┆ 57       ┆ och         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 58       ┆ stöd        ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 59       ┆ via         ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 60       ┆ programmet  ┆ Ins_LearningMobility │
│ trial_5 ┆ page_2 ┆ 61       ┆ Erasmus+.   ┆ Ins_LearningMobility │
└─────────┴────────┴──────────┴─────────────┴──────────────────────┘

In [114]:
word_indices = aois[word_index_column].to_list()
words = aois[word_column].to_list()
word_indices

[-1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61]

In [115]:
rm_dict = {
        word_index: {
            'word': word,
            'word_index': word_index,
            'FFD': 0, 'SFD': 0, 'FD': 0, 'FPRT': 0, 'FRT': 0, 'TFT': 0, 'RRT': 0,
            'RPD_inc': 0, 'RPD_exc': 0, 'RBRT': 0, 'Fix': 0, 'FPF': 0, 'RR': 0,
            'FPReg': 0, 'TRC_out': 0, 'TRC_in': 0, 'SL_in': 0, 'SL_out': 0, 'TFC': 0,
        } for word_index, word in zip(word_indices, words)
    }
rm_dict

{-1: {'word': 'Utbildning,',
  'word_index': -1,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 0: {'word': 'studier',
  'word_index': 0,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 1: {'word': 'och',
  'word_index': 1,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 2: {'word': 'praktik',
  'word_index': 2,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 3: {'word': 'i',
  'word_index': 3,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 4: {'word': 'ett',
  'word_index': 4,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 5: {'word': 'annat',
  'word_index': 5,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 6: {'word': 'land',
  'word_index': 6,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 7: {'word': 'är',
  'word_index': 7,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 8: {'word': 'en',
  'word_index': 8,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 9: {'word': 'unik',
  'word_index': 9,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 10: {'word': 'erfarenhet',
  'word_index': 10,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 11: {'word': 'och',
  'word_index': 11,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 12: {'word': 'kan',
  'word_index': 12,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 13: {'word': 'öppna',
  'word_index': 13,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 14: {'word': 'nya',
  'word_index': 14,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 15: {'word': 'horisonter',
  'word_index': 15,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 16: {'word': 'samt',
  'word_index': 16,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 17: {'word': 'ge',
  'word_index': 17,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 18: {'word': 'färdigheter',
  'word_index': 18,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 19: {'word': 'och',
  'word_index': 19,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 20: {'word': 'egenskaper',
  'word_index': 20,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 21: {'word': 'som',
  'word_index': 21,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 22: {'word': 'värdesätts',
  'word_index': 22,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 23: {'word': 'av',
  'word_index': 23,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 24: {'word': 'arbetsgivarna',
  'word_index': 24,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 25: {'word': 'och',
  'word_index': 25,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 26: {'word': 'är',
  'word_index': 26,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 27: {'word': 'viktiga',
  'word_index': 27,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 28: {'word': 'i',
  'word_index': 28,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 29: {'word': 'dagens',
  'word_index': 29,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 30: {'word': 'samhälle,',
  'word_index': 30,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 31: {'word': 'såsom',
  'word_index': 31,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 32: {'word': 'problemlösningsförmåga,',
  'word_index': 32,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 33: {'word': 'anpassningsförmåga,',
  'word_index': 33,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 34: {'word': 'tolerans',
  'word_index': 34,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 35: {'word': 'och',
  'word_index': 35,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 36: {'word': 'självförtroende.',
  'word_index': 36,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 37: {'word': 'Kommissionen',
  'word_index': 37,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 38: {'word': 'uppmuntrar',
  'word_index': 38,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 39: {'word': 'ungdomars',
  'word_index': 39,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 40: {'word': 'rörlighet',
  'word_index': 40,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 41: {'word': 'i',
  'word_index': 41,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 42: {'word': 'utbildningssyfte',
  'word_index': 42,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 43: {'word': 'genom',
  'word_index': 43,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 44: {'word': 'sin',
  'word_index': 44,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 45: {'word': 'politik',
  'word_index': 45,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 46: {'word': 'och',
  'word_index': 46,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 47: {'word': 'sina',
  'word_index': 47,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 48: {'word': 'program,',
  'word_index': 48,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 49: {'word': 'bland',
  'word_index': 49,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 50: {'word': 'annat',
  'word_index': 50,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 51: {'word': 'med',
  'word_index': 51,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 52: {'word': 'hjälp',
  'word_index': 52,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 53: {'word': 'av',
  'word_index': 53,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 54: {'word': 'ett',
  'word_index': 54,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 55: {'word': 'särskilt',
  'word_index': 55,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 56: {'word': 'riktmärke',
  'word_index': 56,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 57: {'word': 'och',
  'word_index': 57,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 58: {'word': 'stöd',
  'word_index': 58,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 59: {'word': 'via',
  'word_index': 59,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 60: {'word': 'programmet',
  'word_index': 60,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0},
 61: {'word': 'Erasmus+.',
  'word_index': 61,
  'FFD': 0,
  'SFD': 0,
  'FD': 0,
  'FPRT': 0,
  'FRT': 0,
  'TFT': 0,
  'RRT': 0,
  'RPD_inc': 0,
  'RPD_exc': 0,
  'RBRT': 0,
  'Fix': 0,
  'FPF': 0,
  'RR': 0,
  'FPReg': 0,
  'TRC_out': 0,
  'TRC_in': 0,
  'SL_in': 0,
  'SL_out': 0,
  'TFC': 0}}

--> Problem: Now a catch-all entry at index -1 would be added, but this removes the first word of the page

## Iteration through pages

In [123]:
#Creating dataframe with just 
stim = sess.stimuli[2]
aois = stim.text_stimulus.aois
words_only = all_tokens_from_aois(aois, trial=stim.trial_id)
words_only = words_only.with_columns(pl.lit(stim.name).alias("stimulus"))

#Only taking fixations on words into account
group_columns = [settings.TRIAL_COL, settings.STIMULUS_COL, settings.PAGE_COL]

only_fix = (
        gaze.events.frame.filter(
            (pl.col("name") == settings.FIXATION)
            & (pl.col(settings.WORD_IDX_COL).is_not_null())
        )
        .with_row_count("fixation_id")
        .sort(group_columns + ["onset"])
    )
only_fix = only_fix.filter(pl.col("trial")=="trial_5")

2026-07-29 14:38:58,774 - py.warnings - PYWARN:WARNING - /tmp/ipykernel_16150/3523474209.py:15: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  .with_row_count("fixation_id")

In [128]:
for page in stim.pages:
    page_idx = f"page_{page.number}"
    page_words = words_only.filter(pl.col("page")==page_idx)
    page_fix = only_fix.filter(pl.col("page")==page_idx)
    rm_df = compute_reading_measures(
        fixations=page_fix,
        aois = page_words,
        word_index_column= "word_idx",
        word_column = "word"
    )
    print(rm_df.head())

shape: (5, 21)
┌──────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word         ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---          ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str          ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞══════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ FRÅN         ┆ 0          ┆ 113 ┆ 113 ┆ … ┆ 2      ┆ 1     ┆ 1      ┆ 3   │
│ KOMMISSIONEN ┆ 1          ┆ 132 ┆ 132 ┆ … ┆ 0      ┆ 1     ┆ -1     ┆ 3   │
│ TILL         ┆ 2          ┆ 461 ┆ 461 ┆ … ┆ 0      ┆ 2     ┆ 2      ┆ 1   │
│ RÅDET:       ┆ 3          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 2     ┆ 3      ┆ 1   │
│ Lägesrapport ┆ 4          ┆ 114 ┆ 0   ┆ … ┆ 1      ┆ 2     ┆ 2      ┆ 5   │
└──────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘
shape: (5, 21)
┌─────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word    ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---     ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str     ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞═════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ studier ┆ 0          ┆ 157 ┆ 0   ┆ … ┆ 0      ┆ 1     ┆ 2      ┆ 2   │
│ och     ┆ 1          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ praktik ┆ 2          ┆ 172 ┆ 172 ┆ … ┆ 0      ┆ 2     ┆ 2      ┆ 1   │
│ i       ┆ 3          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ ett     ┆ 4          ┆ 139 ┆ 139 ┆ … ┆ 0      ┆ 2     ┆ 3      ┆ 1   │
└─────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘
shape: (5, 21)
┌────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word       ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---        ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str        ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ uppmanar   ┆ 0          ┆ 153 ┆ 153 ┆ … ┆ 1      ┆ 1     ┆ 2      ┆ 4   │
│ i          ┆ 1          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ sina       ┆ 2          ┆ 121 ┆ 121 ┆ … ┆ 4      ┆ 2     ┆ -2     ┆ 6   │
│ slutsatser ┆ 3          ┆ 221 ┆ 221 ┆ … ┆ 2      ┆ 3     ┆ 1      ┆ 7   │
│ 2011       ┆ 4          ┆ 119 ┆ 119 ┆ … ┆ 1      ┆ 1     ┆ -2     ┆ 7   │
└────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘
shape: (5, 21)
┌────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word       ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---        ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str        ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ till       ┆ 0          ┆ 120 ┆ 120 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 1   │
│ rådets     ┆ 1          ┆ 173 ┆ 173 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 1   │
│ slutsatser ┆ 2          ┆ 219 ┆ 219 ┆ … ┆ 0      ┆ 1     ┆ 2      ┆ 1   │
│ från       ┆ 3          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ 2011       ┆ 4          ┆ 220 ┆ 220 ┆ … ┆ 0      ┆ 2     ┆ 2      ┆ 1   │
└────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘
shape: (5, 21)
┌──────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word         ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---          ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str          ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞══════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ denna        ┆ 0          ┆ 112 ┆ 112 ┆ … ┆ 1      ┆ 1     ┆ 1      ┆ 2   │
│ rapport      ┆ 1          ┆ 146 ┆ 146 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 2   │
│ fullgör      ┆ 2          ┆ 274 ┆ 274 ┆ … ┆ 0      ┆ 1     ┆ 3      ┆ 1   │
│ kommissionen ┆ 3          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ sin          ┆ 4          ┆ 0   ┆ 0   ┆ … ┆ 1      ┆ -1    ┆ 3      ┆ 1   │
└──────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘
shape: (5, 21)
┌─────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word        ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---         ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str         ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞═════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ består      ┆ 0          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ av          ┆ 1          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ två         ┆ 2          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ indikatorer ┆ 3          ┆ 149 ┆ 149 ┆ … ┆ 0      ┆ 4     ┆ 2      ┆ 1   │
│ och         ┆ 4          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
└─────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘
shape: (5, 21)
┌────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word       ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---        ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str        ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ ”Senast    ┆ 0          ┆ 127 ┆ 127 ┆ … ┆ 2      ┆ 1     ┆ 1      ┆ 3   │
│ 2020       ┆ 1          ┆ 166 ┆ 166 ┆ … ┆ 1      ┆ 1     ┆ -1     ┆ 4   │
│ bör        ┆ 2          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
│ ett        ┆ 3          ┆ 137 ┆ 137 ┆ … ┆ 0      ┆ 2     ┆ 1      ┆ 1   │
│ genomsnitt ┆ 4          ┆ 129 ┆ 129 ┆ … ┆ 1      ┆ 1     ┆ 2      ┆ 2   │
└────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘
shape: (5, 21)
┌─────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word        ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---         ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str         ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞═════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ avser       ┆ 0          ┆ 0   ┆ 0   ┆ … ┆ 1      ┆ -1    ┆ -1     ┆ 2   │
│ främst      ┆ 1          ┆ 116 ┆ 116 ┆ … ┆ 0      ┆ 2     ┆ -1     ┆ 2   │
│ antalet     ┆ 2          ┆ 165 ┆ 165 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 1   │
│ utresande   ┆ 3          ┆ 168 ┆ 168 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 1   │
│ studerande, ┆ 4          ┆ 323 ┆ 323 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 1   │
└─────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘
shape: (5, 21)
┌───────────────┬────────────┬─────┬─────┬───┬────────┬───────┬────────┬─────┐
│ word          ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TRC_in ┆ SL_in ┆ SL_out ┆ TFC │
│ ---           ┆ ---        ┆ --- ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---    ┆ --- │
│ str           ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64    ┆ i64   ┆ i64    ┆ i64 │
╞═══════════════╪════════════╪═════╪═════╪═══╪════════╪═══════╪════════╪═════╡
│ riktmärke     ┆ 0          ┆ 111 ┆ 111 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 1   │
│ mäter         ┆ 1          ┆ 118 ┆ 118 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 1   │
│ antalet       ┆ 2          ┆ 213 ┆ 213 ┆ … ┆ 0      ┆ 1     ┆ 1      ┆ 1   │
│ utexaminerade ┆ 3          ┆ 132 ┆ 132 ┆ … ┆ 0      ┆ 1     ┆ 2      ┆ 1   │
│ som           ┆ 4          ┆ 0   ┆ 0   ┆ … ┆ 0      ┆ 0     ┆ 0      ┆ 0   │
└───────────────┴────────────┴─────┴─────┴───┴────────┴───────┴────────┴─────┘

## Iteration through stimuli and pages

In [34]:
settings.WORD_IDX_COL

'word_idx'

In [35]:
group_columns = [settings.TRIAL_COL, settings.STIMULUS_COL, settings.PAGE_COL]

only_fix = (
        gaze.events.frame.filter(
            (pl.col("name") == settings.FIXATION)
            & (pl.col(settings.WORD_IDX_COL).is_not_null())
        )
        .with_row_count("fixation_id")
        .sort(group_columns + ["onset"])
    )
only_fix

2026-08-03 09:17:16,121 - py.warnings - PYWARN:WARNING - /tmp/ipykernel_8363/4184453923.py:8: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  .with_row_count("fixation_id")

shape: (6_520, 25)
┌────────────┬────────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ fixation_i ┆ trial      ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word      │
│ d          ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str       │
│ u32        ┆            ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ 0          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Månen     │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆           │
│ 1          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 1        ┆ 1        ┆ 0          ┆ https://e │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆ n.wikiped │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ia.org/wi │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ki/…      │
│ 2          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Månen     │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆           │
│ 3          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 1        ┆ 1        ┆ 0          ┆ https://e │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆ n.wikiped │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ia.org/wi │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ki/…      │
│ 4          ┆ PRACTICE_t ┆ Enc_WikiMo ┆ page_1 ┆ … ┆ 1        ┆ 1        ┆ 0          ┆ https://e │
│            ┆ rial_1     ┆ on_13      ┆        ┆   ┆          ┆          ┆            ┆ n.wikiped │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ia.org/wi │
│            ┆            ┆            ┆        ┆   ┆          ┆          ┆            ┆ ki/…      │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ 5930       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 3        ┆ 57       ┆ 10         ┆ Guds      │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
│ 5931       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 3        ┆ 58       ┆ 11         ┆ namn      │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
│ 5932       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 3        ┆ 59       ┆ 12         ┆ ändå      │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
│ 5933       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 3        ┆ 61       ┆ 14         ┆ bli       │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
│ 5934       ┆ trial_9    ┆ Lit_MagicM ┆ page_6 ┆ … ┆ 4        ┆ 63       ┆ 0          ┆ år!       │
│            ┆            ┆ ountain_6  ┆        ┆   ┆          ┆          ┆            ┆           │
└────────────┴────────────┴────────────┴────────┴───┴──────────┴──────────┴────────────┴───────────┘

In [36]:
rm_all_trials = []

for stim in sess.stimuli:
    aois = stim.text_stimulus.aois
    words_only = all_tokens_from_aois(aois, trial=stim.trial_id)
    words_only = words_only.with_columns(pl.lit(stim.name).alias("stimulus"))
    trial_idx = stim.trial_id

    for page in stim.pages:
        page_idx = f"page_{page.number}"
        page_words = words_only.filter(pl.col("page")==page_idx)
        page_fix = only_fix.filter((pl.col("trial")==trial_idx) & (pl.col("page")==page_idx))
        rm = compute_reading_measures(
            fixations=page_fix,
            aois = page_words,
            word_index_column= "word_idx",
            word_column = "word"
        )
        rm = rm.with_columns(pl.lit(trial_idx).alias("trial"), pl.lit(page_idx).alias("page"), pl.lit(stim.name).alias("stimulus"))
        rm_all_trials.append(rm)

rm_df = pl.concat(rm_all_trials)
rm_df

shape: (5_781, 24)
┌──────────────┬────────────┬─────┬─────┬───┬─────┬──────────────────┬────────┬───────────────────┐
│ word         ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TFC ┆ trial            ┆ page   ┆ stimulus          │
│ ---          ┆ ---        ┆ --- ┆ --- ┆   ┆ --- ┆ ---              ┆ ---    ┆ ---               │
│ str          ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64 ┆ str              ┆ str    ┆ str               │
╞══════════════╪════════════╪═════╪═════╪═══╪═════╪══════════════════╪════════╪═══════════════════╡
│ Namnet       ┆ 0          ┆ 155 ┆ 155 ┆ … ┆ 1   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ ”MultiplEYE” ┆ 1          ┆ 193 ┆ 0   ┆ … ┆ 7   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ är           ┆ 2          ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ en           ┆ 3          ┆ 0   ┆ 0   ┆ … ┆ 1   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ ordlek       ┆ 4          ┆ 162 ┆ 162 ┆ … ┆ 3   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ …            ┆ …          ┆ …   ┆ …   ┆ … ┆ …   ┆ …                ┆ …      ┆ …                 │
│ plats        ┆ 29         ┆ 213 ┆ 213 ┆ … ┆ 1   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ för          ┆ 30         ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ att          ┆ 31         ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ söka         ┆ 32         ┆ 346 ┆ 346 ┆ … ┆ 1   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ skydd.       ┆ 33         ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
└──────────────┴────────────┴─────┴─────┴───┴─────┴──────────────────┴────────┴───────────────────┘

In [148]:
sess.stimuli[0]

Stimulus(id=1, name='PopSci_MultiplEYE', type='experiment', pages=[StimulusPage(number=1, text='MultiplEYE-projektet\n\nNamnet ”MultiplEYE” är en ordlek som kombinerar ”multilingualism” eller ”multiple languages” med ”eye” från ”eye-tracking”. MultiplEYE är en COST-aktion finansierad av den Europeiska unionen. COST-aktioner är forskningsnätverk som stöds av European Cooperation in Science and Technology, förkortat COST. Som finansiär stöder COST vårt växande nätverk av forskare i och utanför Europa genom att ge ekonomiskt stöd till genomförandet av olika networkingevent.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_1_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_1_sv_aoi.png')), StimulusPage(number=2, text='Dessa event omfattar möten i arbetsgrupper, träningskurser för att dela kunskaper med yngre forskare och vetenskapliga forskningsutbyten. Projekttiteln för COST-aktionen MultiplEYE är: Möjliggörande av insamling av flerspråkig eye-trackingdata för forskning på mänsklig och maskinell språkbehandling. Med det menas att syftet för COST-aktionen MultiplEYE är att främja ett interdisciplinärt forskningsnätverk som arbetar med att samla in eye-trackingdata från läsning på flera språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_2_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_2_sv_aoi.png')), StimulusPage(number=3, text='Målet är att stödja utvecklingen av en stor flerspråkig eye-trackingkorpus och göra det möjligt för forskare att samla in data genom att dela med sig av sina kunskaper mellan olika fält, däribland lingvistik, psykologi, tal- och språkpatologi och datavetenskap. Datasamlingen kan sedan användas för att studera mänsklig språkbehandling från ett psykolingvistiskt perspektiv samt för att förbättra och utvärdera maskinell språkbehandling från ett maskininlärningsperspektiv.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_3_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_3_sv_aoi.png')), StimulusPage(number=4, text='Vad är ”eye-tracking”?\nEye-tracking är en metod där man mäter blickpunkten, det vill säga var du tittar, och ögonens rörelser mellan fasta blickpunkter. Den apparat som används för att mäta ögonens position och rörelser kallas eye-tracker. Den består av en infraröd kamera med en ljusfrekvens som varken påverkar eller skadar människoögat.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_4_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_4_sv_aoi.png')), StimulusPage(number=5, text='Med hjälp av algoritmer för bildigenkänning kan eye-trackern med stor precision uppskatta blickpunkterna genom att registrera huvudets och ögonens position, avståndet till den skärm deltagaren tittar på och eye-trackerns position. Eye-tracking är en användbar teknik inom många områden. Den kan till exempel användas för att upptäcka trötthet under bilkörning, eller för att stödja applikationer för screening eller utbildning inom det medicinska området. Eye-tracking används också inom datorspel, marknadsföring och människa-datorinteraktion.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_5_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_5_sv_aoi.png')), StimulusPage(number=6, text='Varför är eye-tracking under läsning särskilt intressant för vårt projekt?\nMedan du läser de här orden följer eye-trackern dina ögonrörelser över texten. Detta ger information om hur lång tid du tittar på en text, eller mer specifikt, hur lång du tittar på varje ord, vilka ord du hoppar över, vilka ord du dröjer vid, och om du behöver gå tillbaka och läsa om delar av texten för att förstå den bättre. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_6_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_6_sv_aoi.png')), StimulusPage(number=7, text='När din hjärna bearbetar textens innehåll återspeglar dina ögonrörelser, nästan i realtid, mycket av den språkliga och kognitiva bearbetning som pågår. Den registrerade datan är således en guldgruva av information om hur vi sätter samman en texts betydelse och grammatiska struktur. Den visar vilka delar av texten som är utmanande och vilka delar som är lättlästa. Efteråt är det upp till forskarna att förklara vilka språkliga faktorer som orsakar vilken typ av ögonrörelser.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_7_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_7_sv_aoi.png')), StimulusPage(number=8, text='Motivationen bakom MultiplEYE är att det fortfarande finns för lite eye-trackingdata, särskilt från språk med färre talare. En datainsamling av denna omfattning är en utmaning när det gäller att utveckla och komma överens om experimentets design, komplexitet och vilka sorters texter som ska läsas av deltagarna. Andra beslut som kan tyckas vara mindre relevanta, men som egentligen är av stor vikt innefattar textstorlek och typsnitt, i vilken ordning texterna presenteras, experimentets genomförande och hur data bearbetas.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_8_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_8_sv_aoi.png')), StimulusPage(number=9, text='När det väl är klart kommer datasamlingen att ge oss möjligheten att undersöka många ämnen kopplade till psykolingvistik och datalingvistik. Till exempel kan vi jämföra läsbeteenden mellan olika språk. Påverkar skriften, till exempel det latinska alfabetet jämfört med kyrilliska eller arabiska alfabet, lästiden? Ett exempel på maskinell behandling av text skulle kunna vara att använda eye-trackingdata i utvecklingen av program baserade på artificiell intelligens som imiterar den mänskliga läsprocessen. Detta skulle kunna användas för att bygga bättre maskinöversättningssystem eller för att förbättra den automatiska extraktionen av nyckelord från en text.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_9_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_9_sv_aoi.png')), StimulusPage(number=10, text='Att få eye-trackingdata från många deltagare, inklusive dig själv, som läser texter på en rad olika språk kommer att utgöra en bra grund för vår forskning. Det kommer att vara den viktigaste faktorn för att göra vårt forskningsnätverk framgångsrikt. Vi hoppas kunna bana väg för forskningsframsteg i en rad av lingvistikens underordnade fält genom att föra samman och stödja en stor grupp av forskare.\n', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_10_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_10_sv_aoi.png')), StimulusPage(number=11, text='De viktigaste resultaten från MultiplEYE-projektet kommer att vara ett stort dataset med eye-trackingdata på många språk och en plattform för nya samarbeten som bygger på denna typ av data. Om du läser denna text stödjer du redan vårt arbete genom att låta oss samla in och analysera dina ögonrörelser medan du läser och förstår språk. Tack!', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_11_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_11_sv_aoi.png'))], text_stimulus=<pymovements.stimulus.text.TextStimulus object at 0x7fcf96530d70>, questions=[ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01111', id='01111', snippet_no=1, question='Vad är en COST-aktion?', target='Det är ett forskningsnätverk som finansieras av den Europeiska unionen.', distractor_a='Det är ett europeiskt forskningsnätverk för tekniska innovationer.', distractor_b='Det är ett forskningsnätverk för eye-tracking på flera språk. ', distractor_c='Det är ett europeiskt nätverk för forskning i läsning på flera språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01111_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01111_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01112', id='01112', snippet_no=1, question='Vad använder medlemmarna i MultiplEYE-projektet en eye-tracker till?', target='Att mäta blickpunkten och ögonens rörelser.', distractor_a='Att mäta huvudets riktning och rörelse under läsning.', distractor_b='Att mäta en texts betydelse och grammatiska struktur. ', distractor_c='Att mäta tanklös läsning av text och hur det påverkar förståelsen. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01112_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01112_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01121', id='01121', snippet_no=1, question='Varför är eye-tracking användbart för att studera språk inom ramen för projektet?', target='Eye-tracking används för att dra slutsatser om hur människor förstår text när de läser.', distractor_a='Eye-tracking används för att identifiera grammatiska fel i texten.', distractor_b='Eye-tracking används för att undersöka likheterna mellan läsning av texter i olika skrifter.', distractor_c='Eye-tracking används för att förstå vad språk betyder för människor. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01121_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01121_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01122', id='01122', snippet_no=1, question='Vad är det övergripande målet för forskarna i MultiplEYE-projektet?', target='Att samla in eye-trackingdata för att främja tvärvetenskaplig forskning i läsning.', distractor_a='Att samla in texter för att främja forskning inom många språkvetenskapliga områden.', distractor_b='Att samla in en ögonrörelsekorpus för att jämföra texter med olika typsnitt och teckenstorlek.', distractor_c='Att samla in eye-trackingdata för att kunna förstå hur människor lär sig nya språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01122_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01122_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01131', id='01131', snippet_no=1, question='Vad är en stor utmaning för MultiplEYE-projektet?', target='Att se till att deltagarna läser bra översättningar av texterna på sina respektive språk.', distractor_a='Att få finansiering till nätverksaktiviteter och forskningsbesök.', distractor_b='Att få ut blickpunkter och deltagarens avstånd till eye-trackern.', distractor_c='Att hantera etiska överväganden kopplade till datasekretess.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01131_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01131_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01132', id='01132', snippet_no=1, question='Vilken information förmedlas i texten?', target='Projektets huvudfokus och infrastruktur för samarbete. ', distractor_a='Mekaniken bakom mänskliga ögonrörelser.', distractor_b='Metoder för att extrahera information från text.', distractor_c='Reglerna för projekt inom ramen för European Cooperation in Science and Technology.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01132_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_131/PopSci_MultiplEYE_id1_question_01132_sv_aoi.png'))], instructions=[Instruction(id=1, name='welcome_screen', text='Välkommen till MultiplEYE-studien\n\n\n\nNär du är redo, tryck på mellanslagstangenten för att komma till instruktionerna.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/welcome_screen_sv.png')), Instruction(id=2, name='empty_screen', text=None, image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/empty_screen_sv.png')), Instruction(id=3, name='fixation_screen', text=None, image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/fixation_screen_sv.png')), Instruction(id=4, name='obligatory_break_screen', text='Du ska nu ta en paus på 5 minuter. Du får gärna ställa dig upp, röra huvudet, låta ögonen slappna av och dricka lite vatten. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/obligatory_break_screen_sv.png')), Instruction(id=5, name='optional_break_screen', text='Du kan nu ta en paus eller ta lite vatten, eller så trycker du på mellanslagstangenten för att fortsätta läsa. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/optional_break_screen_sv.png')), Instruction(id=6, name='final_screen', text='Tack så mycket för din medverkan!\n\nHejdå!', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/final_screen_sv.png')), Instruction(id=7, name='practice_screen', text='Vi kommer nu att inleda med två övningstexter för att du ska få en förståelse för hur experimentet genomförs. Om något är oklart eller om du har frågor kan du prata med försöksledaren.\n\nVänligen titta på den svarta pricken längst ned i det högra hörnet och tryck sedan på mellanslagstangenten för att börja med övningstexterna. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/practice_screen_sv.png')), Instruction(id=8, name='transition_screen', text='\nDu är nu klar med övningstexterna. Experimentet inleds när du är redo. Försök att röra dig så lite som möjligt när du läser texterna. Rör du dig för mycket kan vi behöva omkalibre

## ADD SETTINGS PARAMETERS

In [153]:
group_columns = [settings.TRIAL_COL, settings.STIMULUS_COL, settings.PAGE_COL]

fixation_table = (
        gaze.events.frame.filter(
            (pl.col("name") == settings.FIXATION)
            & (pl.col(settings.WORD_IDX_COL).is_not_null())
        )
        .with_row_count("fixation_id")
        .sort(group_columns + ["onset"])
    )


rm_all_trials = []

for stim in sess.stimuli:
    aois = stim.text_stimulus.aois
    words_only = all_tokens_from_aois(aois, trial=stim.trial_id)
    words_only = words_only.with_columns(pl.lit(stim.name).alias(settings.STIMULUS_COL))
    trial_idx = stim.trial_id

    for page in stim.pages:
        page_idx = f"page_{page.number}"
        page_words = words_only.filter(pl.col(settings.PAGE_COL)==page_idx)
        page_fix = only_fix.filter((pl.col(settings.TRIAL_COL)==trial_idx) & (pl.col(settings.PAGE_COL)==page_idx))
        rm = compute_reading_measures(
            fixations=page_fix,
            aois = page_words,
            word_index_column= settings.WORD_IDX_COL,
            word_column = "word"
        )
        rm = rm.with_columns(pl.lit(trial_idx).alias(settings.TRIAL_COL), pl.lit(page_idx).alias(settings.PAGE_COL), pl.lit(stim.name).alias(settings.STIMULUS_COL))
        rm_all_trials.append(rm)

rm_df = pl.concat(rm_all_trials)
rm_df = rm_df.rename({"word_index":settings.WORD_IDX_COL})
rm_df

2026-07-29 16:04:04,368 - py.warnings - PYWARN:WARNING - /tmp/ipykernel_16150/4074227793.py:8: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  .with_row_count("fixation_id")

shape: (5_781, 24)
┌──────────────┬──────────┬─────┬─────┬───┬─────┬──────────────────┬────────┬───────────────────┐
│ word         ┆ word_idx ┆ FFD ┆ SFD ┆ … ┆ TFC ┆ trial            ┆ page   ┆ stimulus          │
│ ---          ┆ ---      ┆ --- ┆ --- ┆   ┆ --- ┆ ---              ┆ ---    ┆ ---               │
│ str          ┆ i64      ┆ i64 ┆ i64 ┆   ┆ i64 ┆ str              ┆ str    ┆ str               │
╞══════════════╪══════════╪═════╪═════╪═══╪═════╪══════════════════╪════════╪═══════════════════╡
│ Namnet       ┆ 0        ┆ 155 ┆ 155 ┆ … ┆ 1   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ ”MultiplEYE” ┆ 1        ┆ 193 ┆ 0   ┆ … ┆ 7   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ är           ┆ 2        ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ en           ┆ 3        ┆ 0   ┆ 0   ┆ … ┆ 1   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ ordlek       ┆ 4        ┆ 162 ┆ 162 ┆ … ┆ 3   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ …            ┆ …        ┆ …   ┆ …   ┆ … ┆ …   ┆ …                ┆ …      ┆ …                 │
│ plats        ┆ 29       ┆ 213 ┆ 213 ┆ … ┆ 1   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ för          ┆ 30       ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ att          ┆ 31       ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ söka         ┆ 32       ┆ 346 ┆ 346 ┆ … ┆ 1   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ skydd.       ┆ 33       ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
└──────────────┴──────────┴─────┴─────┴───┴─────┴──────────────────┴────────┴───────────────────┘

In [151]:
settings.WORD_IDX_COL

'word_idx'

In [152]:
rm_df.rename({"word_index":settings.WORD_IDX_COL})

shape: (5_781, 24)
┌──────────────┬──────────┬─────┬─────┬───┬─────┬──────────────────┬────────┬───────────────────┐
│ word         ┆ word_idx ┆ FFD ┆ SFD ┆ … ┆ TFC ┆ trial            ┆ page   ┆ stimulus          │
│ ---          ┆ ---      ┆ --- ┆ --- ┆   ┆ --- ┆ ---              ┆ ---    ┆ ---               │
│ str          ┆ i64      ┆ i64 ┆ i64 ┆   ┆ i64 ┆ str              ┆ str    ┆ str               │
╞══════════════╪══════════╪═════╪═════╪═══╪═════╪══════════════════╪════════╪═══════════════════╡
│ Namnet       ┆ 0        ┆ 155 ┆ 155 ┆ … ┆ 1   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ ”MultiplEYE” ┆ 1        ┆ 193 ┆ 0   ┆ … ┆ 7   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ är           ┆ 2        ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ en           ┆ 3        ┆ 0   ┆ 0   ┆ … ┆ 1   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ ordlek       ┆ 4        ┆ 162 ┆ 162 ┆ … ┆ 3   ┆ trial_10         ┆ page_1 ┆ PopSci_MultiplEYE │
│ …            ┆ …        ┆ …   ┆ …   ┆ … ┆ …   ┆ …                ┆ …      ┆ …                 │
│ plats        ┆ 29       ┆ 213 ┆ 213 ┆ … ┆ 1   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ för          ┆ 30       ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ att          ┆ 31       ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ söka         ┆ 32       ┆ 346 ┆ 346 ┆ … ┆ 1   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
│ skydd.       ┆ 33       ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ PRACTICE_trial_2 ┆ page_2 ┆ Lit_NorthWind     │
└──────────────┴──────────┴─────┴─────┴───┴─────┴──────────────────┴────────┴───────────────────┘