# Pre-processing MultiplEYE Data

This notebook provides a step-by-step guide through how to process the eye-tracking data and the psychometric tests data collected within the MultiplEYE project. This goal of this notebook is twofold:

1. To provide a step-by-step guide on how to preprocess MultiplEYE data using the `pymovements` library and our custom preprocessing functions.
2. To serve as a tutorial for researchers who want to preprocess their own MultiplEYE data, or data from other eye-tracking datasets, using the `pymovements` library.

## Preparation steps
1. Download the data folder from the online repository. Note that this is only possible if you have access to at least one data collection protected folder. You will have access if you are an active member of one data collection group. Download the entire content of the folder.
When you download it from SwitchDrive, it will automatically create a .tar file.
2. Add the folder to the `data/` folder in this repo. The name of the folder is the data collection name, e.g., `MultiplEYE_ZH_CH_Zurich_1_2025`.
3. Extract the .tar file in the `data/` folder.
4. Make sure that the folder structure is correct. It should look like the one online and like this (there might be more data but this is not relevant at this point):
```
	MultiplEYE_ZH_CH_Zurich_1_2025/
		documentation/
		eye-tracking-sessions/
			001_.../
			002_.../
			...
			pilot_sessions/
				001_.../
				002_.../
				...
		psychometric-tests-sessions/
		stimuli_MultiplEYE_ZH_CH_Zurich_1_2025/
		...
```

## The config file

The pipeline uses a config file which can be used to specify parameters and settings for the preprocessing. It is typically named `multipleye_settings_preprocessing.yaml`. You can load it explicitly or rely on the default loading mechanism (CWD, environment variable, or legacy root).

Once you have your config file ready, you can load it as shown below.

In [39]:
# from preprocessing.data_collection.multipleye_data_collection import prepare_language_folder
from preprocessing.data_collection.multipleye_data_collection import (
    MultipleyeDataCollection,
)

import preprocessing

# the settings will be loaded into general config module, so we can access all settings at the same place
from preprocessing import settings

from preprocessing.scripts.prepare_language_folder import prepare_language_folder
from preprocessing.metrics.reading.words import all_tokens_from_aois
from pymovements.measure.reading.processing import compute_reading_measures

import polars as pl

In [ ]:
# If you have a specific config file, load it here:
# settings.load_from_yaml("data/MultiplEYE_<...>/multipleye_settings_preprocessing.yaml")

In [2]:
# get the data collection name from the settings and create the path to the data folder
print(f"Active Data Collection: {settings.DATA_COLLECTION_NAME}")
print(f"Dataset Directory: {settings.DATASET_DIR}")

Active Data Collection: MultiplEYE_SV_CH_Zurich_1_2026
Dataset Directory: /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/data/MultiplEYE_SV_CH_Zurich_1_2026

### Inspecting and overriding configuration

After loading the config, you can inspect which sessions are included or excluded, and override these values for the current session without modifying the YAML file.

In [3]:
print(f"Include pilots:  {settings.INCLUDE_PILOTS}")
print(f"Included:        {settings.INCLUDE_SESSIONS}")
print(f"Excluded:        {settings.EXCLUDE_SESSIONS}")
print(f"Output dir:      {settings.OUTPUT_DIR}")
print(f"Run preflight:   {settings.RUN_PREFLIGHT_CHECK}")
print(f"Overwrite:       {settings.OVERWRITE}")

# Override example (uncomment to limit processing to specific sessions):
# settings.INCLUDE_SESSIONS = ["014_DE_DE_1_ET1", "023_DE_DE_1_ET1"]
# settings.EXCLUDE_SESSIONS = []

Include pilots:  True
Included:        ['009_SV_CH_1_ET1']
Excluded:        []
Output dir:      /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026
Run preflight:   True
Overwrite:       True

## MultiplEYE-specific preprocessing & cleaning

In order to be able to run a more generic preprocessing, the MultiplEYE data folder for one language needs to be cleaned and organized in a specific way. Running the script below will:
- unzip session folders if needed
- move session folders from core_sessions folder to the top folder
- check if there is a config file in the stimuli folder (if not, the stimulus folder was probably not uploaded correctly)
- check if there are psychometric tests (if applicable)
	- if necessary, restructure the psychometric test folder.

These steps are very individual for this data collection and results from bugs or changes across the years of collecting data.

Note that executing the cell below for the first time can take very long. However, it will run through quickly after this initial run.

In [4]:
# run the preparation function to prepare the language folder structure
prepare_language_folder()

2026-08-04 09:42:47,169 - preprocessing - INFO - Copying stimulus assets to /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026...

Next, we create a `MultipleyeDataCollection` object from the data folder. This will allow us to easily access the sessions and their information in the next steps.

In [5]:
multipleye = MultipleyeDataCollection.create_from_data_folder(
    settings.DATASET_DIR,
    include_pilots=settings.INCLUDE_PILOTS,
    excluded_sessions=settings.EXCLUDE_SESSIONS,
    included_sessions=settings.INCLUDE_SESSIONS,
)

2026-08-04 09:42:50,319 - preprocessing - INFO - Lab config loaded from /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/config/config_sv_ch_Zurich_1_2026.py
2026-08-04 09:42:50,321 - preprocessing - INFO - JSON lab config loaded from /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/config/MultiplEYE_SV_CH_Zurich_1_2026_lab_configuration.json
2026-08-04 09:42:50,324 - preprocessing - INFO - MultipleyeDataCollection initialized. data_root: /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/data/MultiplEYE_SV_CH_Zurich_1_2026/eye-tracking-sessions
2026-08-04 09:42:50,326 - preprocessing - INFO - Main config loaded from /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/config/config_sv_ch_Zurich_1.py
2026-08-04 09:42:50,330 - preprocessing - WARNING - Folder in eye-tracking-sessions 'tests_sessions' does not match the eye-tracking session regex pattern \d\d\d_SV_CH_1_ET\d(?:_.*)?. Not considered an eye-tracking session.

### Preflight check

Before processing, run a preflight check to validate the dataset structure and catch common issues (missing files, incorrect folder layout, etc.). In case EDF files are missing, you can use `settings.EXCLUDE_SESSIONS = []` to exclude specific sessions, as shown a few cells above.

In [6]:
preprocessing.run_preflight_check(multipleye)

2026-08-04 09:42:59,248 - preprocessing - INFO -
========================================================
  Preflight check — all input files found
========================================================

## Stage 0: Converting EDF to ASC and Preparing Session-Level Information

Stage 0 refers to the initial steps of preprocessing, which involve converting raw eye-tracking data from its original format (e.g., EDF) into a more accessible format (e.g., ASC), and preparing session-level information. This stage is specific to EyeLink eye-trackers and can be omitted for other eye-trackers.

In [7]:
multipleye.convert_edf_to_asc()

2026-08-04 09:45:52,701 - preprocessing - INFO - Starting EDF to ASC conversion for 1 sessions.
Converting EDF to ASC: 100%|██████████| 1/1 [00:00<00:00, 618.63it/s]
2026-08-04 09:45:52,713 - preprocessing - INFO - EDF to ASC conversion completed.

Once this conversion has been completed, we can load all sessions and parse the .asc files.

In [8]:
multipleye.prepare_session_level_information()

Preparing session 009_SV_CH_1_ET1: 100%|██████████| 1/1 [00:09<00:00,  9.51s/it]

In [9]:
# print an overview on the data collection and the sessions
multipleye

Title	MultiplEYE_SV_CH_Zurich_1_2026
Dataset_type	MultiplEYE
Number_of_sessions	0
Number_of_pilots	1
Tested_language	SV
Country	CH
Year	2026
Number of eye-tracking (ET) sessions per participant	1

## Stage 1: Extracting Gaze Samples

In the first preprocessing stage, we extract gaze samples from the .asc files and create a gaze dataframe for each session. This dataframe contains the raw gaze data, including the x and y coordinates of the gaze, the timestamp. We also save the raw gaze data in a separate file for each session.

The next steps are performed for one session only. It is always possible to loop over all sessions and apply the same preprocessing steps to each of them, but for the sake of clarity and simplicity, we will work with one session as an example.

In [10]:
# pick only one session as an example to work with in the next steps
sessions = list(multipleye)  # list of Session objects
sess = sessions[0]  # a real Session
sid = sess.sid  # get the session ID (Sid) from the Session
sid

Sid(pid='009', lang='SV', country='CH', lab='1', session='ET1', session_id=1, postfix='')

In [11]:
type(sess)

preprocessing.data_collection.session.Session

### Creating Gaze Frame from ASCII File

In [12]:
gaze = preprocessing.load_gaze_data(
    asc_file=sess.asc_path,
    lab_config=sess.lab_config,
    sid=sess.sid,
    trial_cols=settings.TRIAL_COLS,
    messages=settings.ANSWER_MSG_PATTERNS,  # for comprehension questions later - see Stage 4.
)

In [13]:
# save gaze and metadata
preprocessing.save_raw_data(sid, gaze)
preprocessing.save_session_metadata(sid, gaze)

In [14]:
sid.raw_data_dir, sid.metadata_dir

(PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/raw_data/009_SV_CH_1_ET1'),
 PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/metadata/009_SV_CH_1_ET1'))

### Output directory structure

All preprocessed data is organised by data type under `preprocessed_data/<data_collection_name>/`. Each data type folder contains one subfolder per session:

```
preprocessed_data/<dcn>/
├── raw_data/
│   └── <session_save_name>/
├── fixations/
│   └── <session_save_name>/
├── saccades/
│   └── <session_save_name>/
├── scanpaths/
│   └── <session_save_name>/
├── reading_measures/
│   └── <session_save_name>/
├── sanity_checks/
│   └── <session_save_name>/
├── metadata/
│   └── <session_save_name>/
│       ├── gaze_metadata.json
│       ├── experiment.yaml
│       ├── calibrations.tsv
│       ├── calibrations.feather
│       ├── validations.tsv
│       ├── validations.feather
│       └── <session_idf>_overview.yaml
├── participant_data.csv
├── <dcn>_overview.yaml
└── stimuli_<dcn>/
```

The `Sid` object provides convenient properties to access each path:

In [15]:
print(f"Raw data:        {sid.raw_data_dir}")
print(f"Metadata:        {sid.metadata_dir}")
print(f"Fixations:       {sid.fixations_dir}")
print(f"Saccades:        {sid.saccades_dir}")
print(f"Scanpaths:       {sid.scanpaths_dir}")
print(f"Reading measures: {sid.reading_measures_dir}")

Raw data:        /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/raw_data/009_SV_CH_1_ET1
Metadata:        /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/metadata/009_SV_CH_1_ET1
Fixations:       /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/fixations/009_SV_CH_1_ET1
Saccades:        /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/saccades/009_SV_CH_1_ET1
Scanpaths:       /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/scanpaths/009_SV_CH_1_ET1
Reading measures: /home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/reading_measures/009_SV_CH_1_ET1

In order to have the metadata which is extracted by pymovements available to create out session overview, we get this information from pymovements and store it in our session object.

In [16]:
sess.pm_gaze_metadata = gaze._metadata
sess.calibrations = gaze.calibrations
sess.validations = gaze.validations

### Coordinate and Velocity Preprocessing

Eye movements are recorded in screen pixel coordinates, which depend on stimulus size and monitor setup. To compare gaze behavior across participants, screens, or datasets, it is standard to convert pixel positions 
into **degrees of visual angle (dva)**. Next, we compute **gaze velocity**, which allows us to detect saccades and distinguish them from fixations.

In [17]:
# inspect the gaze samples
gaze.samples.head()

shape: (5, 9)
┌─────────┬───────┬──────────────┬──────────┬───┬─────────────┬────────┬─────────────┬─────────────┐
│ time    ┆ pupil ┆ stimulus     ┆ activity ┆ … ┆ trial       ┆ page   ┆ session     ┆ pixel       │
│ ---     ┆ ---   ┆ ---          ┆ ---      ┆   ┆ ---         ┆ ---    ┆ ---         ┆ ---         │
│ i64     ┆ f64   ┆ str          ┆ str      ┆   ┆ str         ┆ str    ┆ str         ┆ list[f64]   │
╞═════════╪═══════╪══════════════╪══════════╪═══╪═════════════╪════════╪═════════════╪═════════════╡
│ 2170575 ┆ 652.0 ┆ Enc_WikiMoon ┆ reading  ┆ … ┆ PRACTICE_tr ┆ page_1 ┆ 009_SV_CH_1 ┆ [80.5,      │
│         ┆       ┆ _13          ┆          ┆   ┆ ial_1       ┆        ┆ _ET1        ┆ 103.7]      │
│ 2170576 ┆ 653.0 ┆ Enc_WikiMoon ┆ reading  ┆ … ┆ PRACTICE_tr ┆ page_1 ┆ 009_SV_CH_1 ┆ [81.3,      │
│         ┆       ┆ _13          ┆          ┆   ┆ ial_1       ┆        ┆ _ET1        ┆ 103.2]      │
│ 2170577 ┆ 642.0 ┆ Enc_WikiMoon ┆ reading  ┆ … ┆ PRACTICE_tr ┆ page_1 ┆ 009_SV_CH_1 ┆ [78.3,      │
│         ┆       ┆ _13          ┆          ┆   ┆ ial_1       ┆        ┆ _ET1        ┆ 105.9]      │
│ 2170578 ┆ 645.0 ┆ Enc_WikiMoon ┆ reading  ┆ … ┆ PRACTICE_tr ┆ page_1 ┆ 009_SV_CH_1 ┆ [80.5,      │
│         ┆       ┆ _13          ┆          ┆   ┆ ial_1       ┆        ┆ _ET1        ┆ 106.8]      │
│ 2170579 ┆ 651.0 ┆ Enc_WikiMoon ┆ reading  ┆ … ┆ PRACTICE_tr ┆ page_1 ┆ 009_SV_CH_1 ┆ [78.8,      │
│         ┆       ┆ _13          ┆          ┆   ┆ ial_1       ┆        ┆ _ET1        ┆ 104.4]      │
└─────────┴───────┴──────────────┴──────────┴───┴─────────────┴────────┴─────────────┴─────────────┘

In [18]:
preprocessing.preprocess_gaze(gaze)

In [19]:
# inspect the preprocessed gaze samples, the dataframe should now also contain a position in dva and velocity columns
gaze.samples.head()

shape: (5, 11)
┌─────────┬───────┬─────────────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ time    ┆ pupil ┆ stimulus    ┆ activity ┆ … ┆ session    ┆ pixel      ┆ position   ┆ velocity   │
│ ---     ┆ ---   ┆ ---         ┆ ---      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64     ┆ f64   ┆ str         ┆ str      ┆   ┆ str        ┆ list[f64]  ┆ list[f64]  ┆ list[f64]  │
╞═════════╪═══════╪═════════════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2170575 ┆ 652.0 ┆ Enc_WikiMoo ┆ reading  ┆ … ┆ 009_SV_CH_ ┆ [80.5,     ┆ [-15.11107 ┆ [-0.544006 │
│         ┆       ┆ n_13        ┆          ┆   ┆ 1_ET1      ┆ 103.7]     ┆ 7, -10.470 ┆ , 2.03784] │
│         ┆       ┆             ┆          ┆   ┆            ┆            ┆ 344]       ┆            │
│ 2170576 ┆ 653.0 ┆ Enc_WikiMoo ┆ reading  ┆ … ┆ 009_SV_CH_ ┆ [81.3,     ┆ [-15.09087 ┆ [-0.415798 │
│         ┆       ┆ n_13        ┆          ┆   ┆ 1_ET1      ┆ 103.2]     ┆ 2, -10.483 ┆ ,          │
│         ┆       ┆             ┆          ┆   ┆            ┆            ┆ 245]       ┆ 1.847938]  │
│ 2170577 ┆ 642.0 ┆ Enc_WikiMoo ┆ reading  ┆ … ┆ 009_SV_CH_ ┆ [78.3,     ┆ [-15.16662 ┆ [-0.439114 │
│         ┆       ┆ n_13        ┆          ┆   ┆ 1_ET1      ┆ 105.9]     ┆ 1, -10.413 ┆ ,          │
│         ┆       ┆             ┆          ┆   ┆            ┆            ┆ 566]       ┆ 1.478056]  │
│ 2170578 ┆ 645.0 ┆ Enc_WikiMoo ┆ reading  ┆ … ┆ 009_SV_CH_ ┆ [80.5,     ┆ [-15.11107 ┆ [-0.545122 │
│         ┆       ┆ n_13        ┆          ┆   ┆ 1_ET1      ┆ 106.8]     ┆ 7, -10.390 ┆ , 1.40235] │
│         ┆       ┆             ┆          ┆   ┆            ┆            ┆ 333]       ┆            │
│ 2170579 ┆ 651.0 ┆ Enc_WikiMoo ┆ reading  ┆ … ┆ 009_SV_CH_ ┆ [78.8,     ┆ [-15.154,  ┆ [-0.490519 │
│         ┆       ┆ n_13        ┆          ┆   ┆ 1_ET1      ┆ 104.4]     ┆ -10.452281 ┆ ,          │
│         ┆       ┆             ┆          ┆   ┆            ┆            ┆ ]          ┆ 0.990696]  │
└─────────┴───────┴─────────────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

Save our events data.

In [20]:
gaze = preprocessing.load_trial_level_events_data(
    gaze,
    sess.sid,
    event_type=settings.FIXATION,
    file_pattern=None,
)

gaze = preprocessing.load_trial_level_events_data(
    gaze,
    sess.sid,
    event_type=settings.SACCADE,
    file_pattern=None,
)

## Stage 2b: Map Fixations to AOIs

Once we have the fixations, we can map each of them to the AOIs of the stimulus. The resulting scanpath can then be saved. Note that this features is not yet completely finished.

In [21]:
preprocessing.map_fixations_to_aois(gaze, sess.stimuli)

In [22]:
# The resulting mapping can be stored as a scanpath, which is a sequence of AOIs that were fixated in the order they were fixated.
preprocessing.save_scanpaths(sid, gaze)

In [23]:
# save metadata again
preprocessing.save_session_metadata(sid, gaze)

## NEW

In [24]:
group_columns = [settings.TRIAL_COL, settings.STIMULUS_COL, settings.PAGE_COL]

only_fix = (
    gaze.events.frame.filter(
        (pl.col("name") == settings.FIXATION)
        & (pl.col(settings.WORD_IDX_COL).is_not_null())
    )
    .with_row_count("fixation_id")
    .sort(group_columns + ["onset"])
)
rm_all_trials = []

2026-08-04 09:57:15,510 - py.warnings - PYWARN:WARNING - /tmp/ipykernel_11850/465983878.py:8: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  .with_row_count("fixation_id")

In [37]:
stim = sess.stimuli[0]
aois = stim.text_stimulus.aois
words_only = all_tokens_from_aois(aois, trial=stim.trial_id)
words_only = words_only.with_columns(
    pl.lit(stim.name).alias(settings.STIMULUS_COL)
)
trial_idx = stim.trial_id

In [47]:
trial_fix = only_fix.filter((pl.col(settings.TRIAL_COL) == trial_idx))

In [56]:
grouped_fix = trial_fix.group_by(settings.PAGE_COL)

In [57]:
grouped_fix.head()

shape: (55, 24)
┌────────┬─────────────┬──────────┬────────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ page   ┆ fixation_id ┆ trial    ┆ stimulus   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---    ┆ ---         ┆ ---      ┆ ---        ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ str    ┆ u32         ┆ str      ┆ str        ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│        ┆             ┆          ┆            ┆   ┆          ┆          ┆ i64        ┆            │
╞════════╪═════════════╪══════════╪════════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ page_5 ┆ 617         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ nning      │
│ page_5 ┆ 618         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ nning      │
│ page_5 ┆ 619         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ nning      │
│ page_5 ┆ 620         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 7        ┆ 7          ┆ eye-tracke │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ rn         │
│ page_5 ┆ 621         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ kan        │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆            │
│ …      ┆ …           ┆ …        ┆ …          ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ page_1 ┆ 410         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 1        ┆ 2        ┆ 1          ┆ ”MultiplEY │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ E”         │
│ page_1 ┆ 411         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ MultiplEYE │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ -projektet │
│ page_1 ┆ 412         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 1        ┆ 1        ┆ 0          ┆ Namnet     │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆            │
│ page_1 ┆ 413         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 1        ┆ 2        ┆ 1          ┆ ”MultiplEY │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ E”         │
│ page_1 ┆ 414         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 1        ┆ 4        ┆ 3          ┆ en         │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆            │
└────────┴─────────────┴──────────┴────────────┴───┴──────────┴──────────┴────────────┴────────────┘

In [59]:
settings.PAGE_PREFIX

'page_'

In [58]:
grouped_fix.head()

shape: (55, 24)
┌────────┬─────────────┬──────────┬────────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ page   ┆ fixation_id ┆ trial    ┆ stimulus   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---    ┆ ---         ┆ ---      ┆ ---        ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ str    ┆ u32         ┆ str      ┆ str        ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│        ┆             ┆          ┆            ┆   ┆          ┆          ┆ i64        ┆            │
╞════════╪═════════════╪══════════╪════════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ page_8 ┆ 799         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ bakom      │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆            │
│ page_8 ┆ 800         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 4        ┆ 4          ┆ att        │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆            │
│ page_8 ┆ 801         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ fortfarand │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ e          │
│ page_8 ┆ 802         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 7        ┆ 7          ┆ finns      │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆            │
│ page_8 ┆ 803         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 9        ┆ 9          ┆ lite       │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆            │
│ …      ┆ …           ┆ …        ┆ …          ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ page_5 ┆ 617         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ nning      │
│ page_5 ┆ 618         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ nning      │
│ page_5 ┆ 619         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ nning      │
│ page_5 ┆ 620         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 7        ┆ 7          ┆ eye-tracke │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆ rn         │
│ page_5 ┆ 621         ┆ trial_10 ┆ PopSci_Mul ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ kan        │
│        ┆             ┆          ┆ tiplEYE_1  ┆   ┆          ┆          ┆            ┆            │
└────────┴─────────────┴──────────┴────────────┴───┴──────────┴──────────┴────────────┴────────────┘

In [61]:
for page in grouped_fix:
    print(page)

(('page_10',), shape: (34, 24)
┌────────────┬──────────┬────────────┬─────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_i ┆ trial    ┆ stimulus   ┆ page    ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ d          ┆ ---      ┆ ---        ┆ ---     ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ ---        ┆ str      ┆ str        ┆ str     ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│ u32        ┆          ┆            ┆         ┆   ┆          ┆          ┆ i64        ┆            │
╞════════════╪══════════╪════════════╪═════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 944        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 2        ┆ 2          ┆ eye-tracki │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ngdata     │
│ 945        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 2        ┆ 2          ┆ eye-tracki │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ngdata     │
│ 946        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ få         │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 947        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 2        ┆ 2          ┆ eye-tracki │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ngdata     │
│ 948        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 3        ┆ 3          ┆ från       │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ …          ┆ …        ┆ …          ┆ …       ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 973        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 3        ┆ 45       ┆ 7          ┆ forsknings │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ framsteg   │
│ 974        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 3        ┆ 48       ┆ 10         ┆ rad        │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 975        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 4        ┆ 50       ┆ 0          ┆ lingvistik │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ens        │
│ 976        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 4        ┆ 56       ┆ 6          ┆ samman     │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 977        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 4        ┆ 60       ┆ 10         ┆ stor       │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
└────────────┴──────────┴────────────┴─────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('page_8',), shape: (70, 24)
┌─────────────┬──────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial    ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---      ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str      ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪══════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 799         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ bakom      │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 800         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 0        ┆ 4        ┆ 4          ┆ att        │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 801         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ fortfarand │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ e          │
│ 802         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 0        ┆ 7        ┆ 7          ┆ finns      │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 803         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 0        ┆ 9        ┆ 9          ┆ lite       │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ …           ┆ …        ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 864         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 6        ┆ 70       ┆ 1          ┆ experiment │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ ets        │
│ 865         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 6        ┆ 71       ┆ 2          ┆ genomföran │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ de         │
│ 866         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 6        ┆ 71       ┆ 2          ┆ genomföran │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ de         │
│ 867         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 6        ┆ 74       ┆ 5          ┆ data       │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 868         ┆ trial_10 ┆ PopSci_Mul ┆ page_8 ┆ … ┆ 6        ┆ 75       ┆ 6          ┆ bearbetas. │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
└─────────────┴──────────┴────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('page_3',), shape: (58, 24)
┌─────────────┬──────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial    ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---      ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str      ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪══════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 513         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 0        ┆ 3        ┆ 3          ┆ stödja     │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 514         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 0        ┆ 7        ┆ 7          ┆ stor       │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 515         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 0        ┆ 8        ┆ 8          ┆ flerspråki │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ g          │
│ 516         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 0        ┆ 8        ┆ 8          ┆ flerspråki │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ g          │
│ 517         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 0        ┆ 9        ┆ 9          ┆ eye-tracki │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ ngkorpus   │
│ …           ┆ …        ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 566         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 5        ┆ 60       ┆ 5          ┆ från       │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 567         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 6        ┆ 62       ┆ 0          ┆ maskininlä │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ rningspers │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆            ┆ pektiv.    │
│ 568         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 6        ┆ 62       ┆ 0          ┆ maskininlä │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ rningspers │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆            ┆ pektiv.    │
│ 569         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 6        ┆ 62       ┆ 0          ┆ maskininlä │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ rningspers │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆            ┆ pektiv.    │
│ 570         ┆ trial_10 ┆ PopSci_Mul ┆ page_3 ┆ … ┆ 6        ┆ 62       ┆ 0          ┆ maskininlä │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ rningspers │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆            ┆ pektiv.    │
└─────────────┴──────────┴────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('page_11',), shape: (29, 24)
┌────────────┬──────────┬────────────┬─────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_i ┆ trial    ┆ stimulus   ┆ page    ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ d          ┆ ---      ┆ ---        ┆ ---     ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ ---        ┆ str      ┆ str        ┆ str     ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│ u32        ┆          ┆            ┆         ┆   ┆          ┆          ┆ i64        ┆            │
╞════════════╪══════════╪════════════╪═════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 978        ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ viktigaste │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 979        ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 0        ┆ 8        ┆ 8          ┆ ett        │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 980        ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 1        ┆ 10       ┆ 0          ┆ dataset    │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 981        ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 1        ┆ 12       ┆ 2          ┆ eye-tracki │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ngdata     │
│ 982        ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 1        ┆ 10       ┆ 0          ┆ dataset    │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ …          ┆ …        ┆ …          ┆ …       ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 1002       ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 3        ┆ 46       ┆ 8          ┆ analysera  │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 1003       ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 3        ┆ 48       ┆ 10         ┆ ögonrörels │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ er         │
│ 1004       ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 3        ┆ 50       ┆ 12         ┆ du         │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 1005       ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 4        ┆ 55       ┆ 3          ┆ Tack!      │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 1006       ┆ trial_10 ┆ PopSci_Mul ┆ page_11 ┆ … ┆ 4        ┆ 53       ┆ 1          ┆ förstår    │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
└────────────┴──────────┴────────────┴─────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('page_6',), shape: (43, 24)
┌─────────────┬──────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial    ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---      ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str      ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪══════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 673         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 0        ┆ 4        ┆ 4          ┆ läsning    │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 674         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 0        ┆ 3        ┆ 3          ┆ under      │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 675         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ särskilt   │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 676         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ intressant │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 677         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 0        ┆ 8        ┆ 8          ┆ vårt       │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ …           ┆ …        ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 711         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 4        ┆ 63       ┆ 10         ┆ delar      │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 712         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 4        ┆ 65       ┆ 12         ┆ texten     │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 713         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 4        ┆ 68       ┆ 15         ┆ förstå     │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 714         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 4        ┆ 68       ┆ 15         ┆ förstå     │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 715         ┆ trial_10 ┆ PopSci_Mul ┆ page_6 ┆ … ┆ 5        ┆ 70       ┆ 0          ┆ bättre.    │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
└─────────────┴──────────┴────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('page_5',), shape: (56, 24)
┌─────────────┬──────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial    ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---      ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str      ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪══════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 617         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ nning      │
│ 618         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ nning      │
│ 619         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ bildigenkä │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ nning      │
│ 620         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 0        ┆ 7        ┆ 7          ┆ eye-tracke │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ rn         │
│ 621         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ kan        │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ …           ┆ …        ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 668         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 6        ┆ 65       ┆ 3          ┆ inom       │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 669         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 6        ┆ 66       ┆ 4          ┆ datorspel, │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 670         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 6        ┆ 67       ┆ 5          ┆ marknadsfö │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ ring       │
│ 671         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 7        ┆ 69       ┆ 0          ┆ människa-d │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ atorintera │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆            ┆ ktion.     │
│ 672         ┆ trial_10 ┆ PopSci_Mul ┆ page_5 ┆ … ┆ 7        ┆ 69       ┆ 0          ┆ människa-d │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ atorintera │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆            ┆ ktion.     │
└─────────────┴──────────┴────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('page_2',), shape: (46, 24)
┌─────────────┬──────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial    ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---      ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str      ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪══════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 467         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 0        ┆ 9        ┆ 9          ┆ dela       │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 468         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 1        ┆ 17       ┆ 6          ┆ Projekttit │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ eln        │
│ 469         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 1        ┆ 18       ┆ 7          ┆ för        │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 470         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 1        ┆ 18       ┆ 7          ┆ för        │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 471         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 2        ┆ 19       ┆ 0          ┆ COST-aktio │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ nen        │
│ …           ┆ …        ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 508         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 4        ┆ 47       ┆ 10         ┆ interdisci │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ plinärt    │
│ 509         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 5        ┆ 48       ┆ 0          ┆ forsknings │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ nätverk    │

In [41]:
aois.group_by(settings.PAGE_COL).head()

shape: (55, 12)
┌────────┬──────────┬──────┬────────────┬───┬──────────┬──────────┬────────────────┬───────────────┐
│ page   ┆ char_idx ┆ char ┆ top_left_x ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_in_li ┆ word          │
│ ---    ┆ ---      ┆ ---  ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ne             ┆ ---           │
│ str    ┆ i64      ┆ str  ┆ f64        ┆   ┆ i64      ┆ i64      ┆ ---            ┆ str           │
│        ┆          ┆      ┆            ┆   ┆          ┆          ┆ i64            ┆               │
╞════════╪══════════╪══════╪════════════╪═══╪══════════╪══════════╪════════════════╪═══════════════╡
│ page_1 ┆ 0        ┆ M    ┆ 81.0       ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ MultiplEYE-pr │
│        ┆          ┆      ┆            ┆   ┆          ┆          ┆                ┆ ojektet       │
│ page_1 ┆ 1        ┆ u    ┆ 95.0       ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ MultiplEYE-pr │
│        ┆          ┆      ┆            ┆   ┆          ┆          ┆                ┆ ojektet       │
│ page_1 ┆ 2        ┆ l    ┆ 109.0      ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ MultiplEYE-pr │
│        ┆          ┆      ┆            ┆   ┆          ┆          ┆                ┆ ojektet       │
│ page_1 ┆ 3        ┆ t    ┆ 123.0      ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ MultiplEYE-pr │
│        ┆          ┆      ┆            ┆   ┆          ┆          ┆                ┆ ojektet       │
│ page_1 ┆ 4        ┆ i    ┆ 137.0      ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ MultiplEYE-pr │
│        ┆          ┆      ┆            ┆   ┆          ┆          ┆                ┆ ojektet       │
│ …      ┆ …        ┆ …    ┆ …          ┆ … ┆ …        ┆ …        ┆ …              ┆ …             │
│ page_5 ┆ 0        ┆ M    ┆ 81.0       ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ Med           │
│ page_5 ┆ 1        ┆ e    ┆ 95.0       ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ Med           │
│ page_5 ┆ 2        ┆ d    ┆ 109.0      ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ Med           │
│ page_5 ┆ 3        ┆      ┆ 123.0      ┆ … ┆ 0        ┆ 0        ┆ 0              ┆ Med           │
│ page_5 ┆ 4        ┆ h    ┆ 137.0      ┆ … ┆ 0        ┆ 1        ┆ 1              ┆ hjälp         │
└────────┴──────────┴──────┴────────────┴───┴──────────┴──────────┴────────────────┴───────────────┘

In [ ]:
words_only

In [64]:
for fix in only_fix.group_by(group_columns):
    print(fix)

(('trial_6', 'PopSci_Caveman_12', 'page_4'), shape: (24, 24)
┌─────────────┬─────────┬─────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial   ┆ stimulus    ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---     ┆ ---         ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str     ┆ str         ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆         ┆             ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪═════════╪═════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 2274        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 1        ┆ 15       ┆ 0          ┆ hitta”,    │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 2275        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 1        ┆ 16       ┆ 1          ┆ säger      │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 2276        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 1        ┆ 17       ┆ 2          ┆ Carles     │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 2277        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 1        ┆ 20       ┆ 5          ┆ ledde      │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 2278        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 1        ┆ 21       ┆ 6          ┆ studien    │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ …           ┆ …       ┆ …           ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 2293        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 2        ┆ 29       ┆ 4          ┆ flesta     │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 2294        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 2        ┆ 31       ┆ 6          ┆ teorierna  │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 2295        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 2        ┆ 32       ┆ 7          ┆ visade     │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 2296        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 2        ┆ 34       ┆ 9          ┆ vara       │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 2297        ┆ trial_6 ┆ PopSci_Cave ┆ page_4 ┆ … ┆ 3        ┆ 36       ┆ 0          ┆ felaktiga. │
│             ┆         ┆ man_12      ┆        ┆   ┆          ┆          ┆            ┆ ”          │
└─────────────┴─────────┴─────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('trial_7', 'Ins_HumanRights_2', 'page_3'), shape: (29, 24)
┌─────────────┬─────────┬─────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial   ┆ stimulus    ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---     ┆ ---         ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str     ┆ str         ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆         ┆             ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪═════════╪═════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 1201        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Eftersom   │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 1202        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 0        ┆ 3        ┆ 3          ┆ väsentligt │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 1203        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 0        ┆ 5        ┆ 5          ┆ att        │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 1204        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ människorn │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆ a          │
│ 1205        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 0        ┆ 7        ┆ 7          ┆ inte       │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆            │
│ …           ┆ …       ┆ …           ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 1225        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 2        ┆ 25       ┆ 1          ┆ skyddas    │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆            │
│ 1226        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 2        ┆ 27       ┆ 3          ┆ rättsstate │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆ ns         │
│ 1227        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 2        ┆ 27       ┆ 3          ┆ rättsstate │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆ ns         │
│ 1228        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 2        ┆ 27       ┆ 3          ┆ rättsstate │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆ ns         │
│ 1229        ┆ trial_7 ┆ Ins_HumanRi ┆ page_3 ┆ … ┆ 2        ┆ 28       ┆ 4          ┆ principer, │
│             ┆         ┆ ghts_2      ┆        ┆   ┆          ┆          ┆            ┆            │
└─────────────┴─────────┴─────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('PRACTICE_trial_2', 'Lit_NorthWind_7', 'page_1'), shape: (92, 24)
┌────────────┬────────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ fixation_i ┆ trial      ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word      │
│ d          ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str       │
│ u32        ┆            ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ 1007       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Nordanvin │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆ den       │
│ 1008       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Nordanvin │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆ den       │
│ 1009       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Nordanvin │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆ den       │
│ 1010       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 0        ┆ 2        ┆ 2          ┆ solen     │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆           │
│ 1011       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 1        ┆ 3        ┆ 0          ┆ Mellan    │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆           │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ 1094       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 6        ┆ 74       ┆ 0          ┆ förgäves  │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆           │
│ 1095       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 6        ┆ 75       ┆ 1          ┆ förslösad │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆ e         │
│ 1096       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 6        ┆ 75       ┆ 1          ┆ förslösad │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆ e         │
│ 1097       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 6        ┆ 76       ┆ 2          ┆ sin       │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆           │
│ 1098       ┆ PRACTICE_t ┆ Lit_NorthW ┆ page_1 ┆ … ┆ 6        ┆ 77       ┆ 3          ┆ återståen │
│            ┆ rial_2     ┆ ind_7      ┆        ┆   ┆          ┆          ┆            ┆ de        │
└────────────┴────────────┴────────────┴────────┴───┴──────────┴──────────┴────────────┴───────────┘)
(('trial_9', 'Ins_LearningMobility_3', 'page_2'), shape: (44, 24)
┌─────────────┬─────────┬─────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial   ┆ stimulus    ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---     ┆ ---         ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str     ┆ str         ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆         ┆             ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪═════════╪═════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 4229        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Utbildning │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆ ,          │
│ 4230        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Utbildning │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆ ,          │
│ 4231        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ studier    │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4232        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 3        ┆ 3          ┆ praktik    │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4233        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ annat      │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ …           ┆ …       ┆ …           ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 4268        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 5        ┆ 50       ┆ 3          ┆ bland      │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4269        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 5        ┆ 54       ┆ 7          ┆ av         │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4270        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 6        ┆ 62       ┆ 1          ┆ Erasmus+.  │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4271        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 6        ┆ 61       ┆ 0          ┆ programmet │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4272        ┆ trial_9 ┆ Ins_Learnin ┆ page_2 ┆ … ┆ 6        ┆ 62       ┆ 1          ┆ Erasmus+.  │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
└─────────────┴─────────┴─────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('trial_10', 'PopSci_MultiplEYE_1', 'page_10'), shape: (34, 24)
┌────────────┬──────────┬────────────┬─────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_i ┆ trial    ┆ stimulus   ┆ page    ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ d          ┆ ---      ┆ ---        ┆ ---     ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ ---        ┆ str      ┆ str        ┆ str     ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│ u32        ┆          ┆            ┆         ┆   ┆          ┆          ┆ i64        ┆            │
╞════════════╪══════════╪════════════╪═════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 944        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 2        ┆ 2          ┆ eye-tracki │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ngdata     │
│ 945        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 2        ┆ 2          ┆ eye-tracki │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ngdata     │
│ 946        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ få         │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 947        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 2        ┆ 2          ┆ eye-tracki │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ngdata     │
│ 948        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 0        ┆ 3        ┆ 3          ┆ från       │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ …          ┆ …        ┆ …          ┆ …       ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 973        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 3        ┆ 45       ┆ 7          ┆ forsknings │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ framsteg   │
│ 974        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 3        ┆ 48       ┆ 10         ┆ rad        │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 975        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 4        ┆ 50       ┆ 0          ┆ lingvistik │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆ ens        │
│ 976        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 4        ┆ 56       ┆ 6          ┆ samman     │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
│ 977        ┆ trial_10 ┆ PopSci_Mul ┆ page_10 ┆ … ┆ 4        ┆ 60       ┆ 10         ┆ stor       │
│            ┆          ┆ tiplEYE_1  ┆         ┆   ┆          ┆          ┆            ┆            │
└────────────┴──────────┴────────────┴─────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('trial_9', 'Ins_LearningMobility_3', 'page_5'), shape: (17, 24)
┌─────────────┬─────────┬─────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial   ┆ stimulus    ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---     ┆ ---         ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str     ┆ str         ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆         ┆             ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪═════════╪═════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 4399        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 0        ┆ 0        ┆ 0          ┆ Genom      │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4400        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 0        ┆ 1        ┆ 1          ┆ denna      │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4401        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 0        ┆ 2        ┆ 2          ┆ rapport    │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4402        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 0        ┆ 6        ┆ 6          ┆ skyldighet │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4403        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 0        ┆ 8        ┆ 8          ┆ rapportera │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ …           ┆ …       ┆ …           ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 4411        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 1        ┆ 23       ┆ 12         ┆ riktmärket │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4412        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 2        ┆ 26       ┆ 1          ┆ i          │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4413        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 2        ┆ 25       ┆ 0          ┆ rörlighet  │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
│ 4414        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 2        ┆ 27       ┆ 2          ┆ utbildning │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆ ssyfte     │
│ 4415        ┆ trial_9 ┆ Ins_Learnin ┆ page_5 ┆ … ┆ 2        ┆ 29       ┆ 4          ┆ sikte      │
│             ┆         ┆ gMobility_3 ┆        ┆   ┆          ┆          ┆            ┆            │
└─────────────┴─────────┴─────────────┴────────┴───┴──────────┴──────────┴────────────┴────────────┘)
(('trial_10', 'PopSci_MultiplEYE_1', 'page_2'), shape: (46, 24)
┌─────────────┬──────────┬────────────┬────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ fixation_id ┆ trial    ┆ stimulus   ┆ page   ┆ … ┆ line_idx ┆ word_idx ┆ word_idx_i ┆ word       │
│ ---         ┆ ---      ┆ ---        ┆ ---    ┆   ┆ ---      ┆ ---      ┆ n_line     ┆ ---        │
│ u32         ┆ str      ┆ str        ┆ str    ┆   ┆ i64      ┆ i64      ┆ ---        ┆ str        │
│             ┆          ┆            ┆        ┆   ┆          ┆          ┆ i64        ┆            │
╞═════════════╪══════════╪════════════╪════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 467         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 0        ┆ 9        ┆ 9          ┆ dela       │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 468         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 1        ┆ 17       ┆ 6          ┆ Projekttit │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ eln        │
│ 469         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 1        ┆ 18       ┆ 7          ┆ för        │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 470         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 1        ┆ 18       ┆ 7          ┆ för        │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 471         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 2        ┆ 19       ┆ 0          ┆ COST-aktio │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ nen        │
│ …           ┆ …        ┆ …          ┆ …      ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 508         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 4        ┆ 47       ┆ 10         ┆ interdisci │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ plinärt    │
│ 509         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 5        ┆ 48       ┆ 0          ┆ forsknings │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆ nätverk    │
│ 510         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 5        ┆ 50       ┆ 2          ┆ arbetar    │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │
│ 511         ┆ trial_10 ┆ PopSci_Mul ┆ page_2 ┆ … ┆ 5        ┆ 53       ┆ 5          ┆ samla      │
│             ┆          ┆ tiplEYE_1  ┆        ┆   ┆          ┆          ┆            ┆            │

In [80]:
for (trial_idx, stim_idx, page_idx), df in only_fix.group_by(group_columns):
    words_only = all_tokens_from_aois(df, trial=trial_idx)
    print(words_only.head())

shape: (5, 4)
┌──────────┬────────┬──────────┬────────────────────┐
│ trial    ┆ page   ┆ word_idx ┆ word               │
│ ---      ┆ ---    ┆ ---      ┆ ---                │
│ str      ┆ str    ┆ i64      ┆ str                │
╞══════════╪════════╪══════════╪════════════════════╡
│ trial_10 ┆ page_3 ┆ 3        ┆ stödja             │
│ trial_10 ┆ page_3 ┆ 7        ┆ stor               │
│ trial_10 ┆ page_3 ┆ 8        ┆ flerspråkig        │
│ trial_10 ┆ page_3 ┆ 9        ┆ eye-trackingkorpus │
│ trial_10 ┆ page_3 ┆ 11       ┆ göra               │
└──────────┴────────┴──────────┴────────────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬───────────┐
│ trial   ┆ page   ┆ word_idx ┆ word      │
│ ---     ┆ ---    ┆ ---      ┆ ---       │
│ str     ┆ str    ┆ i64      ┆ str       │
╞═════════╪════════╪══════════╪═══════════╡
│ trial_9 ┆ page_9 ┆ 8        ┆ vistats   │
│ trial_9 ┆ page_9 ┆ 9        ┆ utomlands │
│ trial_9 ┆ page_9 ┆ 12       ┆ studietid │
│ trial_9 ┆ page_9 ┆ 14       ┆ har       │
│ trial_9 ┆ page_9 ┆ 15       ┆ fullföljt │
└─────────┴────────┴──────────┴───────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬──────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word         │
│ ---     ┆ ---    ┆ ---      ┆ ---          │
│ str     ┆ str    ┆ i64      ┆ str          │
╞═════════╪════════╪══════════╪══════════════╡
│ trial_2 ┆ page_5 ┆ 1        ┆ mycket       │
│ trial_2 ┆ page_5 ┆ 2        ┆ riktigt      │
│ trial_2 ┆ page_5 ┆ 7        ┆ upptäckten   │
│ trial_2 ┆ page_5 ┆ 8        ┆ kretsade     │
│ trial_2 ┆ page_5 ┆ 9        ┆ Ottenskjolds │
└─────────┴────────┴──────────┴──────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬───────────┐
│ trial   ┆ page   ┆ word_idx ┆ word      │
│ ---     ┆ ---    ┆ ---      ┆ ---       │
│ str     ┆ str    ┆ i64      ┆ str       │
╞═════════╪════════╪══════════╪═══════════╡
│ trial_4 ┆ page_9 ┆ 12       ┆ sångerna  │
│ trial_4 ┆ page_9 ┆ 14       ┆ om        │
│ trial_4 ┆ page_9 ┆ 15       ┆ Kanun,    │
│ trial_4 ┆ page_9 ┆ 16       ┆ förfärlig │
│ trial_4 ┆ page_9 ┆ 18       ┆ så        │
└─────────┴────────┴──────────┴───────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬───────────┐
│ trial   ┆ page   ┆ word_idx ┆ word      │
│ ---     ┆ ---    ┆ ---      ┆ ---       │
│ str     ┆ str    ┆ i64      ┆ str       │
╞═════════╪════════╪══════════╪═══════════╡
│ trial_6 ┆ page_2 ┆ 11       ┆ livsmedel │
│ trial_6 ┆ page_2 ┆ 12       ┆ än        │
│ trial_6 ┆ page_2 ┆ 14       ┆ bönder    │
│ trial_6 ┆ page_2 ┆ 15       ┆ som       │
│ trial_6 ┆ page_2 ┆ 16       ┆ ändrade   │
└─────────┴────────┴──────────┴───────────┘
shape: (5, 4)
┌─────────┬─────────┬──────────┬──────────────────┐
│ trial   ┆ page    ┆ word_idx ┆ word             │
│ ---     ┆ ---     ┆ ---      ┆ ---              │
│ str     ┆ str     ┆ i64      ┆ str              │
╞═════════╪═════════╪══════════╪══════════════════╡
│ trial_5 ┆ page_11 ┆ 1        ┆ av               │
│ trial_5 ┆ page_11 ┆ 3        ┆ senaste          │
│ trial_5 ┆ page_11 ┆ 8        ┆ mjölkdrickandets │
│ trial_5 ┆ page_11 ┆ 9        ┆ effekter         │
│ trial_5 ┆ page_11 ┆ 10       ┆ publicerades     │
└─────────┴─────────┴──────────┴──────────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬──────────┐
│ trial   ┆ page   ┆ word_idx ┆ word     │
│ ---     ┆ ---    ┆ ---      ┆ ---      │
│ str     ┆ str    ┆ i64      ┆ str      │
╞═════════╪════════╪══════════╪══════════╡
│ trial_6 ┆ page_5 ┆ 1        ┆ spanska  │
│ trial_6 ┆ page_5 ┆ 13       ┆ snubblat │
│ trial_6 ┆ page_5 ┆ 14       ┆ över     │
│ trial_6 ┆ page_5 ┆ 16       ┆ skelett  │
│ trial_6 ┆ page_5 ┆ 18       ┆ ett      │
└─────────┴────────┴──────────┴──────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬───────────┐
│ trial   ┆ page   ┆ word_idx ┆ word      │
│ ---     ┆ ---    ┆ ---      ┆ ---       │
│ str     ┆ str    ┆ i64      ┆ str       │
╞═════════╪════════╪══════════╪═══════════╡
│ trial_7 ┆ page_7 ┆ 0        ┆ Eftersom  │
│ trial_7 ┆ page_7 ┆ 2        ┆ gemensam  │
│ trial_7 ┆ page_7 ┆ 11       ┆ är        │
│ trial_7 ┆ page_7 ┆ 13       ┆ största   │
│ trial_7 ┆ page_7 ┆ 14       ┆ betydelse │
└─────────┴────────┴──────────┴───────────┘
shape: (5, 4)
┌─────────┬─────────┬──────────┬─────────────┐
│ trial   ┆ page    ┆ word_idx ┆ word        │
│ ---     ┆ ---     ┆ ---      ┆ ---         │
│ str     ┆ str     ┆ i64      ┆ str         │
╞═════════╪═════════╪══════════╪═════════════╡
│ trial_5 ┆ page_13 ┆ 1        ┆ är          │
│ trial_5 ┆ page_13 ┆ 2        ┆ allvarliga  │
│ trial_5 ┆ page_13 ┆ 12       ┆ resultaten. │
│ trial_5 ┆ page_13 ┆ 14       ┆ finns       │
│ trial_5 ┆ page_13 ┆ 16       ┆ alltmer     │
└─────────┴─────────┴──────────┴─────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬──────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word         │
│ ---     ┆ ---    ┆ ---      ┆ ---          │
│ str     ┆ str    ┆ i64      ┆ str          │
╞═════════╪════════╪══════════╪══════════════╡
│ trial_5 ┆ page_1 ┆ 2        ┆ Introduktion │
│ trial_5 ┆ page_1 ┆ 4        ┆ vissa        │
│ trial_5 ┆ page_1 ┆ 5        ┆ håll,        │
│ trial_5 ┆ page_1 ┆ 6        ┆ t.ex.        │
│ trial_5 ┆ page_1 ┆ 11       ┆ vanligt      │
└─────────┴────────┴──────────┴──────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬────────┐
│ trial   ┆ page   ┆ word_idx ┆ word   │
│ ---     ┆ ---    ┆ ---      ┆ ---    │
│ str     ┆ str    ┆ i64      ┆ str    │
╞═════════╪════════╪══════════╪════════╡
│ trial_8 ┆ page_4 ┆ 1        ┆ jag    │
│ trial_8 ┆ page_4 ┆ 2        ┆ tittar │
│ trial_8 ┆ page_4 ┆ 4        ┆ genom  │
│ trial_8 ┆ page_4 ┆ 6        ┆ idag   │
│ trial_8 ┆ page_4 ┆ 9        ┆ det    │
└─────────┴────────┴──────────┴────────┘
shape: (5, 4)
┌──────────────────┬────────┬──────────┬──────────────┐
│ trial            ┆ page   ┆ word_idx ┆ word         │
│ ---              ┆ ---    ┆ ---      ┆ ---          │
│ str              ┆ str    ┆ i64      ┆ str          │
╞══════════════════╪════════╪══════════╪══════════════╡
│ PRACTICE_trial_2 ┆ page_1 ┆ 0        ┆ Nordanvinden │
│ PRACTICE_trial_2 ┆ page_1 ┆ 2        ┆ solen        │
│ PRACTICE_trial_2 ┆ page_1 ┆ 3        ┆ Mellan       │
│ PRACTICE_trial_2 ┆ page_1 ┆ 4        ┆ Nordanvinden │
│ PRACTICE_trial_2 ┆ page_1 ┆ 6        ┆ Solen        │
└──────────────────┴────────┴──────────┴──────────────┘
shape: (5, 4)
┌─────────┬─────────┬──────────┬────────────┐
│ trial   ┆ page    ┆ word_idx ┆ word       │
│ ---     ┆ ---     ┆ ---      ┆ ---        │
│ str     ┆ str     ┆ i64      ┆ str        │
╞═════════╪═════════╪══════════╪════════════╡
│ trial_2 ┆ page_12 ┆ 1        ┆ när        │
│ trial_2 ┆ page_12 ┆ 2        ┆ biologerna │
│ trial_2 ┆ page_12 ┆ 4        ┆ den        │
│ trial_2 ┆ page_12 ┆ 6        ┆ ett        │
│ trial_2 ┆ page_12 ┆ 7        ┆ primitivt  │
└─────────┴─────────┴──────────┴────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬───────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word          │
│ ---     ┆ ---    ┆ ---      ┆ ---           │
│ str     ┆ str    ┆ i64      ┆ str           │
╞═════════╪════════╪══════════╪═══════════════╡
│ trial_4 ┆ page_5 ┆ 1        ┆ handen        │
│ trial_4 ┆ page_5 ┆ 4        ┆ makens        │
│ trial_4 ┆ page_5 ┆ 5        ┆ tryckte       │
│ trial_4 ┆ page_5 ┆ 7        ┆ sig           │
│ trial_4 ┆ page_5 ┆ 10       ┆ sammetsklädda │
└─────────┴────────┴──────────┴───────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word       │
│ ---     ┆ ---    ┆ ---      ┆ ---        │
│ str     ┆ str    ┆ i64      ┆ str        │
╞═════════╪════════╪══════════╪════════════╡
│ trial_6 ┆ page_6 ┆ 12       ┆ innan      │
│ trial_6 ┆ page_6 ┆ 13       ┆ jordbruket │
│ trial_6 ┆ page_6 ┆ 14       ┆ hade       │
│ trial_6 ┆ page_6 ┆ 18       ┆ Europa     │
│ trial_6 ┆ page_6 ┆ 19       ┆ från       │
└─────────┴────────┴──────────┴────────────┘
shape: (5, 4)
┌─────────┬─────────┬──────────┬──────────────┐
│ trial   ┆ page    ┆ word_idx ┆ word         │
│ ---     ┆ ---     ┆ ---      ┆ ---          │
│ str     ┆ str     ┆ i64      ┆ str          │
╞═════════╪═════════╪══════════╪══════════════╡
│ trial_2 ┆ page_14 ┆ 0        ┆ Under        │
│ trial_2 ┆ page_14 ┆ 2        ┆ tvist,       │
│ trial_2 ┆ page_14 ┆ 4        ┆ under        │
│ trial_2 ┆ page_14 ┆ 6        ┆ av           │
│ trial_2 ┆ page_14 ┆ 14       ┆ auktoriteter │
└─────────┴─────────┴──────────┴──────────────┘
shape: (5, 4)
┌──────────┬────────┬──────────┬───────────────┐
│ trial    ┆ page   ┆ word_idx ┆ word          │
│ ---      ┆ ---    ┆ ---      ┆ ---           │
│ str      ┆ str    ┆ i64      ┆ str           │
╞══════════╪════════╪══════════╪═══════════════╡
│ trial_10 ┆ page_2 ┆ 9        ┆ dela          │
│ trial_10 ┆ page_2 ┆ 17       ┆ Projekttiteln │
│ trial_10 ┆ page_2 ┆ 18       ┆ för           │
│ trial_10 ┆ page_2 ┆ 19       ┆ COST-aktionen │
│ trial_10 ┆ page_2 ┆ 20       ┆ MultiplEYE    │
└──────────┴────────┴──────────┴───────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬─────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word        │
│ ---     ┆ ---    ┆ ---      ┆ ---         │
│ str     ┆ str    ┆ i64      ┆ str         │
╞═════════╪════════╪══════════╪═════════════╡
│ trial_2 ┆ page_4 ┆ 1        ┆ upprepade   │
│ trial_2 ┆ page_4 ┆ 2        ┆ nu          │
│ trial_2 ┆ page_4 ┆ 4        ┆ allra       │
│ trial_2 ┆ page_4 ┆ 5        ┆ största     │
│ trial_2 ┆ page_4 ┆ 6        ┆ noggrannhet │
└─────────┴────────┴──────────┴─────────────┘
shape: (5, 4)
┌─────────┬─────────┬──────────┬──────────────┐
│ trial   ┆ page    ┆ word_idx ┆ word         │
│ ---     ┆ ---     ┆ ---      ┆ ---          │
│ str     ┆ str     ┆ i64      ┆ str          │
╞═════════╪═════════╪══════════╪══════════════╡
│ trial_8 ┆ page_12 ┆ 0        ┆ Befolkningen │
│ trial_8 ┆ page_12 ┆ 2        ┆ minskat      │
│ trial_8 ┆ page_12 ┆ 3        ┆ till         │
│ trial_8 ┆ page_12 ┆ 4        ┆ några        │
│ trial_8 ┆ page_12 ┆ 5        ┆ tusen        │
└─────────┴─────────┴──────────┴──────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬──────────────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word                 │
│ ---     ┆ ---    ┆ ---      ┆ ---                  │
│ str     ┆ str    ┆ i64      ┆ str                  │
╞═════════╪════════╪══════════╪══════════════════════╡
│ trial_5 ┆ page_2 ┆ 0        ┆ www.gardsmejeriet.se │
│ trial_5 ┆ page_2 ┆ 1        ┆ GÅRDSMEJERIET        │
│ trial_5 ┆ page_2 ┆ 2        ┆ Näringsvärdet        │
│ trial_5 ┆ page_2 ┆ 4        ┆ mjölk:               │
│ trial_5 ┆ page_2 ┆ 6        ┆ nyttigt              │
└─────────┴────────┴──────────┴──────────────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬───────────┐
│ trial   ┆ page   ┆ word_idx ┆ word      │
│ ---     ┆ ---    ┆ ---      ┆ ---       │
│ str     ┆ str    ┆ i64      ┆ str       │
╞═════════╪════════╪══════════╪═══════════╡
│ trial_6 ┆ page_7 ┆ 12       ┆ folket.   │
│ trial_6 ┆ page_7 ┆ 13       ┆ "Man      │
│ trial_6 ┆ page_7 ┆ 15       ┆ många     │
│ trial_6 ┆ page_7 ┆ 16       ┆ avbilder  │
│ trial_6 ┆ page_7 ┆ 18       ┆ människor │
└─────────┴────────┴──────────┴───────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬─────────┐
│ trial   ┆ page   ┆ word_idx ┆ word    │
│ ---     ┆ ---    ┆ ---      ┆ ---     │
│ str     ┆ str    ┆ i64      ┆ str     │
╞═════════╪════════╪══════════╪═════════╡
│ trial_6 ┆ page_8 ┆ 5        ┆ vidare  │
│ trial_6 ┆ page_8 ┆ 12       ┆ med     │
│ trial_6 ┆ page_8 ┆ 13       ┆ moderna │
│ trial_6 ┆ page_8 ┆ 21       ┆ hur     │
│ trial_6 ┆ page_8 ┆ 23       ┆ skulle  │
└─────────┴────────┴──────────┴─────────┘
shape: (5, 4)
┌──────────┬────────┬──────────┬────────────┐
│ trial    ┆ page   ┆ word_idx ┆ word       │
│ ---      ┆ ---    ┆ ---      ┆ ---        │
│ str      ┆ str    ┆ i64      ┆ str        │
╞══════════╪════════╪══════════╪════════════╡
│ trial_10 ┆ page_6 ┆ 3        ┆ under      │
│ trial_10 ┆ page_6 ┆ 4        ┆ läsning    │
│ trial_10 ┆ page_6 ┆ 5        ┆ särskilt   │
│ trial_10 ┆ page_6 ┆ 6        ┆ intressant │
│ trial_10 ┆ page_6 ┆ 8        ┆ vårt       │
└──────────┴────────┴──────────┴────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬───────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word          │
│ ---     ┆ ---    ┆ ---      ┆ ---           │
│ str     ┆ str    ┆ i64      ┆ str           │
╞═════════╪════════╪══════════╪═══════════════╡
│ trial_7 ┆ page_1 ┆ 0        ┆ Allmän        │
│ trial_7 ┆ page_1 ┆ 1        ┆ förklaring    │
│ trial_7 ┆ page_1 ┆ 4        ┆ mänskliga     │
│ trial_7 ┆ page_1 ┆ 5        ┆ rättigheterna │
│ trial_7 ┆ page_1 ┆ 7        ┆ Ingress       │
└─────────┴────────┴──────────┴───────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬─────────┐
│ trial   ┆ page   ┆ word_idx ┆ word    │
│ ---     ┆ ---    ┆ ---      ┆ ---     │
│ str     ┆ str    ┆ i64      ┆ str     │
╞═════════╪════════╪══════════╪═════════╡
│ trial_1 ┆ page_2 ┆ 0        ┆ Detta   │
│ trial_1 ┆ page_2 ┆ 1        ┆ skulle  │
│ trial_1 ┆ page_2 ┆ 3        ┆ vara    │
│ trial_1 ┆ page_2 ┆ 4        ┆ någon   │
│ trial_1 ┆ page_2 ┆ 5        ┆ nackdel │
└─────────┴────────┴──────────┴─────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬────────┐
│ trial   ┆ page   ┆ word_idx ┆ word   │
│ ---     ┆ ---    ┆ ---      ┆ ---    │
│ str     ┆ str    ┆ i64      ┆ str    │
╞═════════╪════════╪══════════╪════════╡
│ trial_5 ┆ page_5 ┆ 0        ┆ Enligt │
│ trial_5 ┆ page_5 ┆ 1        ┆ Bill   │
│ trial_5 ┆ page_5 ┆ 2        ┆ Sears, │
│ trial_5 ┆ page_5 ┆ 3        ┆ läkare │
│ trial_5 ┆ page_5 ┆ 5        ┆ docent │
└─────────┴────────┴──────────┴────────┘
shape: (5, 4)
┌─────────┬─────────┬──────────┬─────────┐
│ trial   ┆ page    ┆ word_idx ┆ word    │
│ ---     ┆ ---     ┆ ---      ┆ ---     │
│ str     ┆ str     ┆ i64      ┆ str     │
╞═════════╪═════════╪══════════╪═════════╡
│ trial_4 ┆ page_10 ┆ 0        ┆ Däremot │
│ trial_4 ┆ page_10 ┆ 9        ┆ alla    │
│ trial_4 ┆ page_10 ┆ 12       ┆ road    │
│ trial_4 ┆ page_10 ┆ 13       ┆ min     │
│ trial_4 ┆ page_10 ┆ 14       ┆ som     │
└─────────┴─────────┴──────────┴─────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬────────────────────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word                       │
│ ---     ┆ ---    ┆ ---      ┆ ---                        │
│ str     ┆ str    ┆ i64      ┆ str                        │
╞═════════╪════════╪══════════╪════════════════════════════╡
│ trial_5 ┆ page_8 ┆ 0        ┆ www.halsoaktuellt.se/mjolk │
│ trial_5 ┆ page_8 ┆ 1        ┆ HÄLSOAKTUELLT              │
│ trial_5 ┆ page_8 ┆ 3        ┆ NEJ                        │
│ trial_5 ┆ page_8 ┆ 5        ┆ KOMJÖLK!                   │
│ trial_5 ┆ page_8 ┆ 7        ┆ dr                         │
└─────────┴────────┴──────────┴────────────────────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬─────────┐
│ trial   ┆ page   ┆ word_idx ┆ word    │
│ ---     ┆ ---    ┆ ---      ┆ ---     │
│ str     ┆ str    ┆ i64      ┆ str     │
╞═════════╪════════╪══════════╪═════════╡
│ trial_4 ┆ page_1 ┆ 0        ┆ Grymma  │
│ trial_4 ┆ page_1 ┆ 1        ┆ april   │
│ trial_4 ┆ page_1 ┆ 3        ┆ Kapitel │
│ trial_4 ┆ page_1 ┆ 5        ┆ Med     │
│ trial_4 ┆ page_1 ┆ 7        ┆ hustrus │
└─────────┴────────┴──────────┴─────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬─────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word        │
│ ---     ┆ ---    ┆ ---      ┆ ---         │
│ str     ┆ str    ┆ i64      ┆ str         │
╞═════════╪════════╪══════════╪═════════════╡
│ trial_7 ┆ page_5 ┆ 0        ┆ Eftersom    │
│ trial_7 ┆ page_5 ┆ 1        ┆ Förenta     │
│ trial_7 ┆ page_5 ┆ 2        ┆ Nationernas │
│ trial_7 ┆ page_5 ┆ 3        ┆ folk        │
│ trial_7 ┆ page_5 ┆ 5        ┆ stadgan     │
└─────────┴────────┴──────────┴─────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬─────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word        │
│ ---     ┆ ---    ┆ ---      ┆ ---         │
│ str     ┆ str    ┆ i64      ┆ str         │
╞═════════╪════════╪══════════╪═════════════╡
│ trial_4 ┆ page_3 ┆ 1        ┆ och         │
│ trial_4 ┆ page_3 ┆ 3        ┆ pärlade     │
│ trial_4 ┆ page_3 ┆ 4        ┆ små         │
│ trial_4 ┆ page_3 ┆ 5        ┆ regndroppar │
│ trial_4 ┆ page_3 ┆ 6        ┆ över        │
└─────────┴────────┴──────────┴─────────────┘
shape: (5, 4)
┌──────────┬────────┬──────────┬─────────────────┐
│ trial    ┆ page   ┆ word_idx ┆ word            │
│ ---      ┆ ---    ┆ ---      ┆ ---             │
│ str      ┆ str    ┆ i64      ┆ str             │
╞══════════╪════════╪══════════╪═════════════════╡
│ trial_10 ┆ page_5 ┆ 5        ┆ bildigenkänning │
│ trial_10 ┆ page_5 ┆ 6        ┆ kan             │
│ trial_10 ┆ page_5 ┆ 7        ┆ eye-trackern    │
│ trial_10 ┆ page_5 ┆ 9        ┆ stor            │
│ trial_10 ┆ page_5 ┆ 10       ┆ precision       │
└──────────┴────────┴──────────┴─────────────────┘
shape: (5, 4)
┌─────────┬─────────┬──────────┬─────────────────────┐
│ trial   ┆ page    ┆ word_idx ┆ word                │
│ ---     ┆ ---     ┆ ---      ┆ ---                 │
│ str     ┆ str     ┆ i64      ┆ str                 │
╞═════════╪═════════╪══════════╪═════════════════════╡
│ trial_5 ┆ page_12 ┆ 1        ┆ amerikanska         │
│ trial_5 ┆ page_12 ┆ 2        ┆ läkarorganisationen │
│ trial_5 ┆ page_12 ┆ 4        ┆ ansvarsfull         │
│ trial_5 ┆ page_12 ┆ 5        ┆ sjukvård            │
│ trial_5 ┆ page_12 ┆ 7        ┆ (Physicians         │
└─────────┴─────────┴──────────┴─────────────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬─────────┐
│ trial   ┆ page   ┆ word_idx ┆ word    │
│ ---     ┆ ---    ┆ ---      ┆ ---     │
│ str     ┆ str    ┆ i64      ┆ str     │
╞═════════╪════════╪══════════╪═════════╡
│ trial_1 ┆ page_5 ┆ 0        ┆ Därtill │
│ trial_1 ┆ page_5 ┆ 1        ┆ kan     │
│ trial_1 ┆ page_5 ┆ 2        ┆ det     │
│ trial_1 ┆ page_5 ┆ 3        ┆ hända   │
│ trial_1 ┆ page_5 ┆ 5        ┆ vår     │
└─────────┴────────┴──────────┴─────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word       │
│ ---     ┆ ---    ┆ ---      ┆ ---        │
│ str     ┆ str    ┆ i64      ┆ str        │
╞═════════╪════════╪══════════╪════════════╡
│ trial_4 ┆ page_7 ┆ 0        ┆ När        │
│ trial_4 ┆ page_7 ┆ 1        ┆ fästmannen │
│ trial_4 ┆ page_7 ┆ 7        ┆ avslöjat   │
│ trial_4 ┆ page_7 ┆ 9        ┆ planer     │
│ trial_4 ┆ page_7 ┆ 11       ┆ henne      │
└─────────┴────────┴──────────┴────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬────────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word           │
│ ---     ┆ ---    ┆ ---      ┆ ---            │
│ str     ┆ str    ┆ i64      ┆ str            │
╞═════════╪════════╪══════════╪════════════════╡
│ trial_5 ┆ page_4 ┆ 0        ┆ Gårdsmejeriets │
│ trial_5 ┆ page_4 ┆ 3        ┆ ökad           │
│ trial_5 ┆ page_4 ┆ 4        ┆ viktminskning  │
│ trial_5 ┆ page_4 ┆ 6        ┆ bidrar         │
│ trial_5 ┆ page_4 ┆ 8        ┆ att            │
└─────────┴────────┴──────────┴────────────────┘
shape: (5, 4)
┌─────────┬────────┬──────────┬───────────────────┐
│ trial   ┆ page   ┆ word_idx ┆ word              │
│ ---     ┆ ---    ┆ ---      ┆ ---               │
│ str     ┆ str    ┆ i64      ┆ str               │
╞═════════╪════════╪══════════╪═══════════════════╡
│ trial_2 ┆ page_9 ┆ 0        ┆ Bristen           │
│ trial_2 ┆ page_9 ┆ 1        ┆ på                │
│ trial_2 ┆ page_9 ┆ 2        ┆ medel             │
│ trial_2 ┆ page_9 ┆ 3        ┆ försenade         │
│ trial_2 ┆ page_9 ┆ 8        ┆ Solarisexpedition │
└─────────┴────────┴──────────┴───────────────────┘
shape: (5, 4)
┌──────────┬─────────┬──────────┬──────────────────┐
│ trial    ┆ page    ┆ word_idx ┆ word             │
│ ---      ┆ ---     ┆ ---      ┆ ---              │
│ str      ┆ str     ┆ i64      ┆ str              │
╞══════════╪═════════╪══════════╪══════════════════╡

In [74]:
stimuli = sess.stimuli
stim = stimuli[0]
stim

Stimulus(id=1, name='PopSci_MultiplEYE', type='experiment', pages=[StimulusPage(number=1, text='MultiplEYE-projektet\n\nNamnet ”MultiplEYE” är en ordlek som kombinerar ”multilingualism” eller ”multiple languages” med ”eye” från ”eye-tracking”. MultiplEYE är en COST-aktion finansierad av den Europeiska unionen. COST-aktioner är forskningsnätverk som stöds av European Cooperation in Science and Technology, förkortat COST. Som finansiär stöder COST vårt växande nätverk av forskare i och utanför Europa genom att ge ekonomiskt stöd till genomförandet av olika networkingevent.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_1_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_1_sv_aoi.png')), StimulusPage(number=2, text='Dessa event omfattar möten i arbetsgrupper, träningskurser för att dela kunskaper med yngre forskare och vetenskapliga forskningsutbyten. Projekttiteln för COST-aktionen MultiplEYE är: Möjliggörande av insamling av flerspråkig eye-trackingdata för forskning på mänsklig och maskinell språkbehandling. Med det menas att syftet för COST-aktionen MultiplEYE är att främja ett interdisciplinärt forskningsnätverk som arbetar med att samla in eye-trackingdata från läsning på flera språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_2_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_2_sv_aoi.png')), StimulusPage(number=3, text='Målet är att stödja utvecklingen av en stor flerspråkig eye-trackingkorpus och göra det möjligt för forskare att samla in data genom att dela med sig av sina kunskaper mellan olika fält, däribland lingvistik, psykologi, tal- och språkpatologi och datavetenskap. Datasamlingen kan sedan användas för att studera mänsklig språkbehandling från ett psykolingvistiskt perspektiv samt för att förbättra och utvärdera maskinell språkbehandling från ett maskininlärningsperspektiv.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_3_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_3_sv_aoi.png')), StimulusPage(number=4, text='Vad är ”eye-tracking”?\nEye-tracking är en metod där man mäter blickpunkten, det vill säga var du tittar, och ögonens rörelser mellan fasta blickpunkter. Den apparat som används för att mäta ögonens position och rörelser kallas eye-tracker. Den består av en infraröd kamera med en ljusfrekvens som varken påverkar eller skadar människoögat.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_4_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_4_sv_aoi.png')), StimulusPage(number=5, text='Med hjälp av algoritmer för bildigenkänning kan eye-trackern med stor precision uppskatta blickpunkterna genom att registrera huvudets och ögonens position, avståndet till den skärm deltagaren tittar på och eye-trackerns position. Eye-tracking är en användbar teknik inom många områden. Den kan till exempel användas för att upptäcka trötthet under bilkörning, eller för att stödja applikationer för screening eller utbildning inom det medicinska området. Eye-tracking används också inom datorspel, marknadsföring och människa-datorinteraktion.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_5_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_5_sv_aoi.png')), StimulusPage(number=6, text='Varför är eye-tracking under läsning särskilt intressant för vårt projekt?\nMedan du läser de här orden följer eye-trackern dina ögonrörelser över texten. Detta ger information om hur lång tid du tittar på en text, eller mer specifikt, hur lång du tittar på varje ord, vilka ord du hoppar över, vilka ord du dröjer vid, och om du behöver gå tillbaka och läsa om delar av texten för att förstå den bättre. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_6_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_6_sv_aoi.png')), StimulusPage(number=7, text='När din hjärna bearbetar textens innehåll återspeglar dina ögonrörelser, nästan i realtid, mycket av den språkliga och kognitiva bearbetning som pågår. Den registrerade datan är således en guldgruva av information om hur vi sätter samman en texts betydelse och grammatiska struktur. Den visar vilka delar av texten som är utmanande och vilka delar som är lättlästa. Efteråt är det upp till forskarna att förklara vilka språkliga faktorer som orsakar vilken typ av ögonrörelser.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_7_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_7_sv_aoi.png')), StimulusPage(number=8, text='Motivationen bakom MultiplEYE är att det fortfarande finns för lite eye-trackingdata, särskilt från språk med färre talare. En datainsamling av denna omfattning är en utmaning när det gäller att utveckla och komma överens om experimentets design, komplexitet och vilka sorters texter som ska läsas av deltagarna. Andra beslut som kan tyckas vara mindre relevanta, men som egentligen är av stor vikt innefattar textstorlek och typsnitt, i vilken ordning texterna presenteras, experimentets genomförande och hur data bearbetas.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_8_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_8_sv_aoi.png')), StimulusPage(number=9, text='När det väl är klart kommer datasamlingen att ge oss möjligheten att undersöka många ämnen kopplade till psykolingvistik och datalingvistik. Till exempel kan vi jämföra läsbeteenden mellan olika språk. Påverkar skriften, till exempel det latinska alfabetet jämfört med kyrilliska eller arabiska alfabet, lästiden? Ett exempel på maskinell behandling av text skulle kunna vara att använda eye-trackingdata i utvecklingen av program baserade på artificiell intelligens som imiterar den mänskliga läsprocessen. Detta skulle kunna användas för att bygga bättre maskinöversättningssystem eller för att förbättra den automatiska extraktionen av nyckelord från en text.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_9_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_9_sv_aoi.png')), StimulusPage(number=10, text='Att få eye-trackingdata från många deltagare, inklusive dig själv, som läser texter på en rad olika språk kommer att utgöra en bra grund för vår forskning. Det kommer att vara den viktigaste faktorn för att göra vårt forskningsnätverk framgångsrikt. Vi hoppas kunna bana väg för forskningsframsteg i en rad av lingvistikens underordnade fält genom att föra samman och stödja en stor grupp av forskare.\n', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_10_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_10_sv_aoi.png')), StimulusPage(number=11, text='De viktigaste resultaten från MultiplEYE-projektet kommer att vara ett stort dataset med eye-trackingdata på många språk och en plattform för nya samarbeten som bygger på denna typ av data. Om du läser denna text stödjer du redan vårt arbete genom att låta oss samla in och analysera dina ögonrörelser medan du läser och förstår språk. Tack!', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/stimuli_images_sv_ch_1/popsci_multipleye_id1_page_11_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_stimuli_images_sv_ch_1/popsci_multipleye_id1_page_11_sv_aoi.png'))], text_stimulus=<pymovements.stimulus.text.TextStimulus object at 0x7f7281be41a0>, questions=[ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01111', id='01111', snippet_no=1, question='Vad är en COST-aktion?', target='Det är ett forskningsnätverk som finansieras av den Europeiska unionen.', distractor_a='Det är ett europeiskt forskningsnätverk för tekniska innovationer.', distractor_b='Det är ett forskningsnätverk för eye-tracking på flera språk. ', distractor_c='Det är ett europeiskt nätverk för forskning i läsning på flera språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01111_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01111_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01112', id='01112', snippet_no=1, question='Vad använder medlemmarna i MultiplEYE-projektet en eye-tracker till?', target='Att mäta blickpunkten och ögonens rörelser.', distractor_a='Att mäta huvudets riktning och rörelse under läsning.', distractor_b='Att mäta en texts betydelse och grammatiska struktur. ', distractor_c='Att mäta tanklös läsning av text och hur det påverkar förståelsen. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01112_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01112_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01121', id='01121', snippet_no=1, question='Varför är eye-tracking användbart för att studera språk inom ramen för projektet?', target='Eye-tracking används för att dra slutsatser om hur människor förstår text när de läser.', distractor_a='Eye-tracking används för att identifiera grammatiska fel i texten.', distractor_b='Eye-tracking används för att undersöka likheterna mellan läsning av texter i olika skrifter.', distractor_c='Eye-tracking används för att förstå vad språk betyder för människor. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01121_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01121_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01122', id='01122', snippet_no=1, question='Vad är det övergripande målet för forskarna i MultiplEYE-projektet?', target='Att samla in eye-trackingdata för att främja tvärvetenskaplig forskning i läsning.', distractor_a='Att samla in texter för att främja forskning inom många språkvetenskapliga områden.', distractor_b='Att samla in en ögonrörelsekorpus för att jämföra texter med olika typsnitt och teckenstorlek.', distractor_c='Att samla in eye-trackingdata för att kunna förstå hur människor lär sig nya språk.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01122_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01122_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01131', id='01131', snippet_no=1, question='Vad är en stor utmaning för MultiplEYE-projektet?', target='Att se till att deltagarna läser bra översättningar av texterna på sina respektive språk.', distractor_a='Att få finansiering till nätverksaktiviteter och forskningsbesök.', distractor_b='Att få ut blickpunkter och deltagarens avstånd till eye-trackern.', distractor_c='Att hantera etiska överväganden kopplade till datasekretess.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01131_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01131_sv_aoi.png')), ComprehensionQuestion(name='MPRC_PopSci_MultiplEYE_sv_01132', id='01132', snippet_no=1, question='Vilken information förmedlas i texten?', target='Projektets huvudfokus och infrastruktur för samarbete. ', distractor_a='Mekaniken bakom mänskliga ögonrörelser.', distractor_b='Metoder för att extrahera information från text.', distractor_c='Reglerna för projekt inom ramen för European Cooperation in Science and Technology.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01132_sv.png'), aoi_image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/aoi_question_images_sv_ch_1/question_images_version_128/PopSci_MultiplEYE_id1_question_01132_sv_aoi.png'))], instructions=[Instruction(id=1, name='welcome_screen', text='Välkommen till MultiplEYE-studien\n\n\n\nNär du är redo, tryck på mellanslagstangenten för att komma till instruktionerna.', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/welcome_screen_sv.png')), Instruction(id=2, name='empty_screen', text=None, image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/empty_screen_sv.png')), Instruction(id=3, name='fixation_screen', text=None, image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/fixation_screen_sv.png')), Instruction(id=4, name='obligatory_break_screen', text='Du ska nu ta en paus på 5 minuter. Du får gärna ställa dig upp, röra huvudet, låta ögonen slappna av och dricka lite vatten. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/obligatory_break_screen_sv.png')), Instruction(id=5, name='optional_break_screen', text='Du kan nu ta en paus eller ta lite vatten, eller så trycker du på mellanslagstangenten för att fortsätta läsa. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/optional_break_screen_sv.png')), Instruction(id=6, name='final_screen', text='Tack så mycket för din medverkan!\n\nHejdå!', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/final_screen_sv.png')), Instruction(id=7, name='practice_screen', text='Vi kommer nu att inleda med två övningstexter för att du ska få en förståelse för hur experimentet genomförs. Om något är oklart eller om du har frågor kan du prata med försöksledaren.\n\nVänligen titta på den svarta pricken längst ned i det högra hörnet och tryck sedan på mellanslagstangenten för att börja med övningstexterna. ', image_path=PosixPath('/home/antonia/Dokumente/Arbeit/multipleye-preprocessing/preprocessed_data/MultiplEYE_SV_CH_Zurich_1_2026/stimuli_MultiplEYE_SV_CH_Zurich_1_2026/participant_instructions_images_sv_ch_1/practice_screen_sv.png')), Instruction(id=8, name='transition_screen', text='\nDu är nu klar med övningstexterna. Experimentet inleds när du är redo. Försök att röra dig så lite som möjligt när du läser texterna. Rör du dig för mycket kan vi behöva omkalibre

In [77]:
aois = stim.text_stimulus.aois
words_only = all_tokens_from_aois(aois, trial=stim.trial_id)
words_only = words_only.with_columns(
    pl.lit(stim.name).alias(settings.STIMULUS_COL)
)
trial_idx = stim.trial_id

In [79]:
words_only

shape: (737, 5)
┌──────────┬─────────┬──────────┬──────────────────────┬───────────────────┐
│ trial    ┆ page    ┆ word_idx ┆ word                 ┆ stimulus          │
│ ---      ┆ ---     ┆ ---      ┆ ---                  ┆ ---               │
│ str      ┆ str     ┆ i64      ┆ str                  ┆ str               │
╞══════════╪═════════╪══════════╪══════════════════════╪═══════════════════╡
│ trial_10 ┆ page_5  ┆ 0        ┆ Med                  ┆ PopSci_MultiplEYE │
│ trial_10 ┆ page_11 ┆ 0        ┆ De                   ┆ PopSci_MultiplEYE │
│ trial_10 ┆ page_2  ┆ 0        ┆ Dessa                ┆ PopSci_MultiplEYE │
│ trial_10 ┆ page_1  ┆ 0        ┆ MultiplEYE-projektet ┆ PopSci_MultiplEYE │
│ trial_10 ┆ page_8  ┆ 0        ┆ Motivationen         ┆ PopSci_MultiplEYE │
│ …        ┆ …       ┆ …        ┆ …                    ┆ …                 │
│ trial_10 ┆ page_9  ┆ 85       ┆ av                   ┆ PopSci_MultiplEYE │
│ trial_10 ┆ page_9  ┆ 86       ┆ nyckelord            ┆ PopSci_MultiplEYE │
│ trial_10 ┆ page_9  ┆ 87       ┆ från                 ┆ PopSci_MultiplEYE │
│ trial_10 ┆ page_9  ┆ 88       ┆ en                   ┆ PopSci_MultiplEYE │
│ trial_10 ┆ page_9  ┆ 89       ┆ text.                ┆ PopSci_MultiplEYE │
└──────────┴─────────┴──────────┴──────────────────────┴───────────────────┘

In [82]:
rm_all_trials = []

for (trial_idx, stim_name, page_idx), df in only_fix.group_by(group_columns):
    words_only = all_tokens_from_aois(df, trial=trial_idx)
    rm = compute_reading_measures(
        fixations=df,
        aois=words_only,
        word_index_column=settings.WORD_IDX_COL,
        word_column="word",
    )
    rm = rm.with_columns(
        pl.lit(trial_idx).alias(settings.TRIAL_COL),
        pl.lit(page_idx).alias(settings.PAGE_COL),
        pl.lit(stim_name).alias(settings.STIMULUS_COL),
    )
    rm_all_trials.append(rm)

In [83]:
rm_df = pl.concat(rm_all_trials)
rm_df

shape: (3_423, 24)
┌────────────────┬────────────┬─────┬─────┬───┬─────┬─────────┬────────┬────────────────────────┐
│ word           ┆ word_index ┆ FFD ┆ SFD ┆ … ┆ TFC ┆ trial   ┆ page   ┆ stimulus               │
│ ---            ┆ ---        ┆ --- ┆ --- ┆   ┆ --- ┆ ---     ┆ ---    ┆ ---                    │
│ str            ┆ i64        ┆ i64 ┆ i64 ┆   ┆ i64 ┆ str     ┆ str    ┆ str                    │
╞════════════════╪════════════╪═════╪═════╪═══╪═════╪═════════╪════════╪════════════════════════╡
│ mjölkprodukter ┆ 0          ┆ 199 ┆ 199 ┆ … ┆ 1   ┆ trial_5 ┆ page_3 ┆ Arg_PISACowsMilk_10    │
│ innehåller     ┆ 1          ┆ 194 ┆ 194 ┆ … ┆ 1   ┆ trial_5 ┆ page_3 ┆ Arg_PISACowsMilk_10    │
│ viktiga        ┆ 2          ┆ 209 ┆ 209 ┆ … ┆ 1   ┆ trial_5 ┆ page_3 ┆ Arg_PISACowsMilk_10    │
│ kalcium,       ┆ 5          ┆ 196 ┆ 196 ┆ … ┆ 1   ┆ trial_5 ┆ page_3 ┆ Arg_PISACowsMilk_10    │
│ D,             ┆ 8          ┆ 117 ┆ 117 ┆ … ┆ 1   ┆ trial_5 ┆ page_3 ┆ Arg_PISACowsMilk_10    │
│ …              ┆ …          ┆ …   ┆ …   ┆ … ┆ …   ┆ …       ┆ …      ┆ …                      │
│ separata       ┆ 80         ┆ 331 ┆ 331 ┆ … ┆ 1   ┆ trial_9 ┆ page_3 ┆ Ins_LearningMobility_3 │
│ dokument       ┆ 81         ┆ 213 ┆ 213 ┆ … ┆ 1   ┆ trial_9 ┆ page_3 ┆ Ins_LearningMobility_3 │
│ finns          ┆ 83         ┆ 170 ┆ 170 ┆ … ┆ 1   ┆ trial_9 ┆ page_3 ┆ Ins_LearningMobility_3 │
│ tillgängliga   ┆ 84         ┆ 300 ┆ 300 ┆ … ┆ 1   ┆ trial_9 ┆ page_3 ┆ Ins_LearningMobility_3 │
│ hos            ┆ 85         ┆ 155 ┆ 155 ┆ … ┆ 1   ┆ trial_9 ┆ page_3 ┆ Ins_LearningMobility_3 │
└────────────────┴────────────┴─────┴─────┴───┴─────┴─────────┴────────┴────────────────────────┘

## Stage 3: Calculate AOI-based Measures

In this last step, we calculate the aoi-based measures. These are also refered to as reading measures, as they are typically used in reading research. They include measures such as first pass fixation duration (FPF), total fixation count (TFC), regression path duration (RPD), and many more. These measures are calculated based on the fixations that were mapped to the AOIs in the previous step.

### Fixation-based Metrics

As an intermediate step, the fixations are annotated. These annoataions include:
- The run ID. This ID specifies continuous sequences of fixations on the same word. It is used to calculate first pass and second pass measures.
- Whether the fixation is within the first pass or not
- The index of the preceding word and the following word
- If the saccade entering or leaving the fixation is a regression or not
- Whether it is the first fixation on the word or not

This information is necessary to calculate the reading measures in the next step.

In [ ]:
rm_df = preprocessing.calculate_reading_measures(gaze, sess.stimuli)
preprocessing.save_reading_measures(sid, rm_df)

In [ ]:
rm_df.filter(pl.col("trial") == "trial_1").head()

## Stage 4: Comprehension Question Answers
In addition to gaze data, each session contains answers to comprehension questions.
These are extracted from the ASC messages. The answers are matched to the stimulus order using the `question_order_versions.csv` file in the session's logfiles folder.

In [ ]:
answers_csv = sid.answers_dir / f"{sid}_answers.csv"
question_order_csv = (
    sess.session_folder_path / "logfiles" / "question_order_versions.csv"
)
parsed_answers = preprocessing.parse_answers_from_messages(gaze.messages)
source = "asc"

In [ ]:
parsed_answers

In [ ]:
preprocessing.collect_session_answers(
    question_order_csv=question_order_csv,
    stimuli_trial_map=sess.stimuli_trial_mapping,
    stimuli=sess.stimuli,
    parsed_answers=parsed_answers,
    out_path=answers_csv,
    source=source,
    completed_stimuli_ids=sess.completed_stimuli_ids,
)

## Final Steps

In the very end, we can create the session and dataset overview and store them as well. In addition, the participant data can be parsed and stored.

For the MultiplEYE data, there is also the option to create a sanity check report.

In [ ]:
multipleye.create_sanity_check_report(
    gaze,
    sess.session_identifier,
    output_dir=settings.OUTPUT_DIR,
    plotting=True,
    overwrite=True,
)

In [ ]:
multipleye.create_session_overview(sess.session_identifier, path=settings.OUTPUT_DIR)
multipleye.create_dataset_overview(path=settings.OUTPUT_DIR)
multipleye.parse_participant_data(settings.OUTPUT_DIR / "participant_data.csv")

In [ ]:
from preprocessing.psychometric_tests.preprocess_psychometric_tests import (
    preprocess_all_sessions,
)

preprocess_all_sessions()